namespace TmrOverlay.Core.Overlays;

internal static class OverlayBehaviorDescriptorCatalog
{
    private static readonly IReadOnlyList<OverlayBehaviorDescriptor> Descriptors =
    [
        new(
            Id: "standings",
            BodyKind: "table",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.ChromeMayRenderWithoutBodyData,
            ChromePolicy: OverlayChromePolicy.HeaderFooterConfigurable,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.SettingsSessionFilters,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["rowIdentities", "columnKeys", "classHeaders", "referenceRow"]),
        new(
            Id: "relative",
            BodyKind: "table",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.ChromeMayRenderWithoutBodyData,
            ChromePolicy: OverlayChromePolicy.HeaderFooterConfigurable,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.SettingsSessionFilters,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["rowIdentities", "gapText", "lapRelationship", "referenceRow"]),
        new(
            Id: "fuel-calculator",
            BodyKind: "metrics",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.HiddenWhenNoLocalContext,
            ChromePolicy: OverlayChromePolicy.HeaderFooterConfigurable,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.LocalContextRequired,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["metricSections", "strategySource", "localContext", "modelReadiness"]),
        new(
            Id: "session-weather",
            BodyKind: "metrics",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.HiddenWhenNoMeaningfulData,
            ChromePolicy: OverlayChromePolicy.HeaderFooterConfigurable,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.SettingsSessionFilters,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["metricSections", "sessionState", "weatherSource"]),
        new(
            Id: "pit-service",
            BodyKind: "metrics",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.HiddenWhenNoLocalContext,
            ChromePolicy: OverlayChromePolicy.HeaderFooterConfigurable,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.LocalContextRequired,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["serviceRows", "tireInventory", "refuelRecommendation", "localContext"]),
        new(
            Id: "input-state",
            BodyKind: "inputs",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.UnavailablePlaceholderAllowed,
            ChromePolicy: OverlayChromePolicy.ContentOnly,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.LocalContextRequired,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["traceBounds", "inputAvailability", "sampleCounts"]),
        new(
            Id: "car-radar",
            BodyKind: "car-radar",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.HiddenWhenNoActiveSignal,
            ChromePolicy: OverlayChromePolicy.ContentOnly,
            SizingPolicy: OverlaySizingPolicy.FixedCanvas,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.LocalContextRequired,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["side", "timeGap", "localContext", "multiclassWarning"]),
        new(
            Id: "gap-to-leader",
            BodyKind: "graph",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.ChromeMayRenderWithoutBodyData,
            ChromePolicy: OverlayChromePolicy.HeaderFooterConfigurable,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.AllSessions,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["rowIdentities", "seriesBounds", "sourceCadence", "focusedCar"]),
        new(
            Id: "track-map",
            BodyKind: "track-map",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.UnavailablePlaceholderAllowed,
            ChromePolicy: OverlayChromePolicy.ContentOnly,
            SizingPolicy: OverlaySizingPolicy.FixedCanvas,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.SettingsSessionFilters,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["markerIds", "focusCar", "mapSource", "vectorBounds"]),
        new(
            Id: "flags",
            BodyKind: "flags",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.HiddenWhenNoActiveSignal,
            ChromePolicy: OverlayChromePolicy.ContentOnly,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.AllSessions,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.RouteAndModelExpected,
            EvidenceFields: ["flagCategories", "activeFlags", "localFlagEvidence"]),
        new(
            Id: "garage-cover",
            BodyKind: "garage-cover",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.NotApplicable,
            NoDataPolicy: OverlayNoDataPolicy.HiddenWhenNoActiveSignal,
            ChromePolicy: OverlayChromePolicy.ContentOnly,
            SizingPolicy: OverlaySizingPolicy.FullCanvasCover,
            ScalePolicy: OverlayScalePolicy.FullCanvasCoverScale,
            SessionPolicy: OverlaySessionPolicy.GarageSignalRequired,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.HiddenOrRenderedStateExpected,
            EvidenceFields: ["shouldCover", "detectionState", "detectionIsFresh", "imageSource"]),
        new(
            Id: "stream-chat",
            BodyKind: "stream-chat",
            BrowserReview: OverlaySurfaceSupport.Supported,
            LocalhostObs: OverlaySurfaceSupport.Supported,
            WindowsNative: OverlaySurfaceSupport.Supported,
            NoDataPolicy: OverlayNoDataPolicy.ExternalProviderDriven,
            ChromePolicy: OverlayChromePolicy.ProviderChrome,
            SizingPolicy: OverlaySizingPolicy.ContractGeometry,
            ScalePolicy: OverlayScalePolicy.VisualScale,
            SessionPolicy: OverlaySessionPolicy.AllSessions,
            ObsReadinessPolicy: OverlayObsReadinessPolicy.ExternalProviderRouteExpected,
            EvidenceFields: ["provider", "connectionState", "messageRows", "hiddenPrivateSettings"])
    ];

    public static IReadOnlyList<OverlayBehaviorDescriptor> All => Descriptors;

    public static bool TryGet(string overlayId, out OverlayBehaviorDescriptor descriptor)
    {
        descriptor = Descriptors.FirstOrDefault(candidate =>
            string.Equals(candidate.Id, overlayId, StringComparison.OrdinalIgnoreCase))!;
        return descriptor is not null;
    }
}
