using System.Globalization;
using System.Reflection;
using TmrOverlay.App.Overlays.BrowserSources;

namespace TmrOverlay.App.Overlays;

internal static class OverlayGeometryContracts
{
    public static OverlayGeometryContract Current => OverlayGeometryContractValues.Current;

    public static GapGraphGeometryContract GapGraph => Current.GapGraph;

    public static MetricRowsGeometryContract MetricRows => Current.MetricRows;

    public static StreamChatGeometryContract StreamChat => Current.StreamChat;

    public static InputStateGeometryContract InputState => Current.InputState;

    public static FlagsGeometryContract Flags => Current.Flags;

    public static CanvasOverlaysGeometryContract CanvasOverlays => Current.CanvasOverlays;

    public static SettingsGeometryContract SettingsGeometry => Current.SettingsGeometry;

    public static OverlaySizesGeometryContract OverlaySizes => Current.OverlaySizes;

    public static TableGeometryContract TableGeometry => Current.TableGeometry;

    public static string BrowserJson()
    {
        return BrowserOverlayAssets.Contract("overlay-geometry.json");
    }

    public static string CssVariables()
    {
        var chat = StreamChat;
        var gap = GapGraph;
        var metrics = MetricRows;
        var input = InputState;
        var flags = Flags;
        var canvas = CanvasOverlays;
        var overlaySizes = OverlaySizes;
        var settings = SettingsGeometry;
        var variables = new Dictionary<string, string>
        {
            ["--tmr-gap-panel-padding-x"] = Px(gap.BrowserPanelPaddingX),
            ["--tmr-gap-panel-padding-y"] = Px(gap.BrowserPanelPaddingY),
            ["--tmr-metric-min-simple-height"] = Px(metrics.MinimumSimpleTelemetryHeight),
            ["--tmr-metric-min-simple-width"] = Px(metrics.MinimumSimpleTelemetryWidth),
            ["--tmr-metric-non-race-height-reduction"] = Px(metrics.NonRaceSimpleTelemetryHeightReduction),
            ["--tmr-metric-pit-service-metric-only-width"] = Px(metrics.PitServiceMetricOnlyWidth),
            ["--tmr-metric-fuel-min-height"] = Px(metrics.MinimumFuelCalculatorHeight),
            ["--tmr-metric-fuel-non-race-height"] = Px(metrics.FuelNonRaceHeight),
            ["--tmr-metric-header-height"] = Px(metrics.HeaderChromeHeight),
            ["--tmr-metric-footer-height"] = Px(metrics.FooterChromeHeight),
            ["--tmr-metric-body-gap"] = Px(metrics.BodyGap),
            ["--tmr-metric-content-padding-x"] = Px(metrics.ContentPaddingX),
            ["--tmr-metric-content-padding-top"] = Px(metrics.ContentPaddingTop),
            ["--tmr-metric-content-padding-bottom"] = Px(metrics.ContentPaddingBottom),
            ["--tmr-metric-collapsed-footer-reserve-height"] = Px(metrics.CollapsedFooterReserveHeight),
            ["--tmr-metric-list-min-width"] = Px(metrics.MetricListMinimumWidth),
            ["--tmr-metric-row-plain-height"] = Px(metrics.PlainRowHeight),
            ["--tmr-metric-row-segmented-height"] = Px(metrics.SegmentedRowHeight),
            ["--tmr-metric-row-directional-height"] = Px(metrics.DirectionalRowHeight),
            ["--tmr-metric-row-gap"] = Px(metrics.RowGap),
            ["--tmr-metric-section-title-height"] = Px(metrics.SectionTitleHeight),
            ["--tmr-metric-section-title-bottom-gap"] = Px(metrics.SectionTitleBottomGap),
            ["--tmr-metric-section-title-inset-x"] = Px(metrics.SectionTitleInsetX),
            ["--tmr-metric-section-gap"] = Px(metrics.SectionGap),
            ["--tmr-metric-row-radius"] = Px(metrics.RowRadius),
            ["--tmr-metric-row-border-width"] = Px(metrics.RowBorderWidth),
            ["--tmr-metric-label-column-width"] = Px(metrics.LabelColumnWidth),
            ["--tmr-metric-label-padding-left"] = Px(metrics.LabelPaddingLeft),
            ["--tmr-metric-label-padding-right"] = Px(metrics.LabelPaddingRight),
            ["--tmr-metric-value-padding-left"] = Px(metrics.ValuePaddingLeft),
            ["--tmr-metric-value-padding-right"] = Px(metrics.ValuePaddingRight),
            ["--tmr-metric-value-divider-width"] = Px(metrics.ValueDividerWidth),
            ["--tmr-metric-cell-padding-y"] = Px(metrics.CellVerticalPadding),
            ["--tmr-metric-value-segment-gap"] = Px(metrics.ValueSegmentGap),
            ["--tmr-metric-pit-service-section-gap"] = Px(metrics.PitServiceSectionGap),
            ["--tmr-metric-grid-gap"] = Px(metrics.MetricGridGap),
            ["--tmr-metric-grid-header-height"] = Px(metrics.MetricGridHeaderHeight),
            ["--tmr-metric-grid-header-bottom-gap"] = Px(metrics.MetricGridHeaderBottomGap),
            ["--tmr-metric-grid-row-height"] = Px(metrics.MetricGridRowHeight),
            ["--tmr-metric-grid-row-gap"] = Px(metrics.MetricGridRowGap),
            ["--tmr-metric-grid-cell-inset"] = Px(metrics.MetricGridCellInset),
            ["--tmr-metric-grid-cell-gap"] = Px(metrics.MetricGridCellGap),
            ["--tmr-metric-grid-cell-min-width"] = Px(metrics.MetricGridCellMinimumWidth),
            ["--tmr-metric-grid-cell-height"] = Px(metrics.MetricGridCellHeight),
            ["--tmr-stream-chat-overlay-width"] = Px(chat.OverlayWidth),
            ["--tmr-stream-chat-overlay-height"] = Px(chat.OverlayHeight),
            ["--tmr-stream-chat-header-height"] = Px(chat.HeaderHeight),
            ["--tmr-stream-chat-header-right-reserve"] = Px(chat.HeaderRightReserve),
            ["--tmr-stream-chat-close-size"] = Px(chat.CloseButtonSize),
            ["--tmr-stream-chat-close-right"] = Px(chat.CloseButtonRight),
            ["--tmr-stream-chat-close-top"] = Px(chat.CloseButtonTop),
            ["--tmr-stream-chat-content-padding-x"] = Px(chat.ContentHorizontalPadding),
            ["--tmr-stream-chat-content-padding-top"] = Px(chat.ContentTopPadding),
            ["--tmr-stream-chat-content-padding-bottom"] = Px(chat.ContentBottomPadding),
            ["--tmr-stream-chat-body-max-height"] = Px(chat.OverlayHeight + 100),
            ["--tmr-stream-chat-body-viewport-height-offset"] = Px(chat.AvailableHeightFallbackOffset),
            ["--tmr-stream-chat-row-gap"] = Px(chat.RowGap),
            ["--tmr-stream-chat-row-min-height"] = Px(chat.RowMinHeight),
            ["--tmr-stream-chat-row-padding-y"] = Px(chat.RowPaddingY),
            ["--tmr-stream-chat-row-padding-x"] = Px(chat.RowPaddingX),
            ["--tmr-stream-chat-row-radius"] = Px(chat.RowRadius),
            ["--tmr-stream-chat-head-gap"] = Px(chat.HeadGap),
            ["--tmr-stream-chat-head-height"] = Px(chat.HeadHeight),
            ["--tmr-stream-chat-head-text-gap"] = Px(chat.HeadTextGap),
            ["--tmr-stream-chat-badge-gap"] = Px(chat.BadgeGap),
            ["--tmr-stream-chat-badge-max-row-fraction"] = chat.BadgeMaxRowFraction.ToString("0.###", CultureInfo.InvariantCulture),
            ["--tmr-stream-chat-badge-max-row-width"] = $"{(chat.BadgeMaxRowFraction * 100f).ToString("0.###", CultureInfo.InvariantCulture)}%",
            ["--tmr-stream-chat-badge-min-width"] = Px(chat.BadgeMinWidth),
            ["--tmr-stream-chat-badge-max-width"] = Px(chat.BadgeMaxWidth),
            ["--tmr-stream-chat-badge-height"] = Px(chat.BadgeHeight),
            ["--tmr-stream-chat-badge-padding-x"] = Px(chat.BadgePaddingX),
            ["--tmr-stream-chat-badge-image-size"] = Px(chat.BadgeImageSize),
            ["--tmr-stream-chat-name-font-size"] = Px(chat.NameFontSize),
            ["--tmr-stream-chat-name-font-weight"] = chat.NameFontWeight.ToString(CultureInfo.InvariantCulture),
            ["--tmr-stream-chat-chip-gap"] = Px(chat.ChipGap),
            ["--tmr-stream-chat-chip-max-width"] = Px(chat.ChipMaxWidth),
            ["--tmr-stream-chat-chip-height"] = Px(chat.ChipHeight),
            ["--tmr-stream-chat-chip-padding-x"] = Px(chat.ChipPaddingX),
            ["--tmr-stream-chat-chip-radius"] = Px(chat.ChipRadius),
            ["--tmr-stream-chat-chip-font-size"] = Px(chat.ChipFontSize),
            ["--tmr-stream-chat-text-font-size"] = Px(chat.TextFontSize),
            ["--tmr-stream-chat-text-line-height"] = Px(chat.TextLineHeight),
            ["--tmr-stream-chat-emote-size"] = Px(chat.EmoteSize),
            ["--tmr-stream-chat-emote-margin-top"] = Px(chat.EmoteMarginTop),
            ["--tmr-stream-chat-emote-margin-x"] = Px(chat.EmoteMarginX),
            ["--tmr-stream-chat-emote-margin-bottom"] = Px(chat.EmoteMarginBottom),
            ["--tmr-settings-design-width"] = Px(settings.DesignWidth),
            ["--tmr-settings-design-height"] = Px(settings.DesignHeight),
            ["--tmr-settings-shell-width"] = Px(settings.ShellWidth),
            ["--tmr-settings-shell-height"] = Px(settings.ShellHeight),
            ["--tmr-settings-shell-corner-radius"] = Px(settings.ShellCornerRadius),
            ["--tmr-settings-titlebar-height"] = Px(settings.TitlebarHeight),
            ["--tmr-settings-body-height"] = Px(settings.BodyHeight),
            ["--tmr-settings-sidebar-width"] = Px(settings.SidebarWidth),
            ["--tmr-settings-sidebar-height"] = Px(settings.SidebarHeight),
            ["--tmr-settings-content-width"] = Px(settings.ContentWidth),
            ["--tmr-settings-content-height"] = Px(settings.ContentHeight),
            ["--tmr-settings-content-header-height"] = Px(settings.ContentHeaderHeight),
            ["--tmr-settings-content-body-height"] = Px(settings.ContentBodyHeight),
            ["--tmr-settings-content-body-padding-top"] = Px(settings.ContentBodyPaddingTop),
            ["--tmr-settings-content-body-with-regions-padding-top"] = Px(settings.ContentBodyWithRegionsPaddingTop),
            ["--tmr-settings-content-body-padding-x"] = Px(settings.ContentBodyPaddingX),
            ["--tmr-settings-content-body-padding-bottom"] = Px(settings.ContentBodyPaddingBottom),
            ["--tmr-settings-panel-small-width"] = Px(settings.PanelSmallWidth),
            ["--tmr-settings-panel-medium-width"] = Px(settings.PanelMediumWidth),
            ["--tmr-settings-panel-wide-width"] = Px(settings.PanelWideWidth),
            ["--tmr-settings-panel-padding-x"] = Px(settings.PanelPaddingX),
            ["--tmr-settings-panel-padding-y"] = Px(settings.PanelPaddingY),
            ["--tmr-settings-panel-title-height"] = Px(settings.PanelTitleHeight),
            ["--tmr-settings-panel-title-bounds-height"] = Px(settings.PanelTitleBoundsHeight),
            ["--tmr-settings-panel-title-padding-bottom"] = Px(settings.PanelTitlePaddingBottom),
            ["--tmr-settings-panel-title-margin-bottom"] = Px(settings.PanelTitleMarginBottom),
            ["--tmr-settings-general-grid-gap"] = Px(settings.GeneralGridGap),
            ["--tmr-settings-general-top-grid-height"] = Px(settings.GeneralTopGridHeight),
            ["--tmr-settings-units-panel-width"] = Px(settings.UnitsPanelWidth),
            ["--tmr-settings-units-panel-height"] = Px(settings.UnitsPanelHeight),
            ["--tmr-settings-updates-panel-width"] = Px(settings.UpdatesPanelWidth),
            ["--tmr-settings-updates-panel-height"] = Px(settings.UpdatesPanelHeight),
            ["--tmr-settings-preview-panel-width"] = Px(settings.PreviewPanelWidth),
            ["--tmr-settings-preview-panel-height"] = Px(settings.PreviewPanelHeight),
            ["--tmr-settings-preview-panel-margin-top"] = Px(settings.PreviewPanelMarginTop),
            ["--tmr-settings-support-panel-height"] = Px(settings.SupportPanelHeight),
            ["--tmr-settings-support-bridge-column-width"] = Px(settings.SupportBridgeColumnWidth),
            ["--tmr-settings-support-bridge-column-gap"] = Px(settings.SupportBridgeColumnGap),
            ["--tmr-settings-support-bridge-row-height"] = Px(settings.SupportBridgeRowHeight),
            ["--tmr-settings-support-bridge-row-stride"] = Px(settings.SupportBridgeRowStride),
            ["--tmr-settings-support-bridge-label-width"] = Px(settings.SupportBridgeLabelWidth),
            ["--tmr-settings-support-bridge-value-width"] = Px(settings.SupportBridgeValueWidth),
            ["--tmr-settings-support-bridge-error-row-offset-y"] = Px(settings.SupportBridgeErrorRowOffsetY),
            ["--tmr-settings-support-bridge-description-offset-y"] = Px(settings.SupportBridgeDescriptionOffsetY),
            ["--tmr-settings-support-bridge-description-line-height"] = Px(settings.SupportBridgeDescriptionLineHeight),
            ["--tmr-settings-support-bridge-description-line-stride"] = Px(settings.SupportBridgeDescriptionLineStride),
            ["--tmr-settings-overlay-controls-panel-height"] = Px(settings.OverlayControlsPanelHeight),
            ["--tmr-settings-garage-overlay-controls-panel-height"] = Px(settings.GarageOverlayControlsPanelHeight),
            ["--tmr-settings-browser-source-panel-width"] = Px(settings.BrowserSourcePanelWidth),
            ["--tmr-settings-browser-source-panel-height"] = Px(settings.BrowserSourcePanelHeight),
            ["--tmr-settings-browser-source-url-height"] = Px(settings.BrowserSourceUrlHeight),
            ["--tmr-settings-browser-source-copy-button-top"] = Px(settings.BrowserSourceCopyButtonTop),
            ["--tmr-settings-browser-source-copy-button-right"] = Px(settings.BrowserSourceCopyButtonRight),
            ["--tmr-settings-content-matrix-width"] = Px(settings.ContentMatrixWidth),
            ["--tmr-settings-content-matrix-minimum-height"] = Px(settings.ContentMatrixMinimumHeight),
            ["--tmr-settings-content-matrix-preview-height"] = Px(settings.ContentMatrixPreviewHeight),
            ["--tmr-settings-chat-inputs-width"] = Px(settings.ChatInputsWidth),
            ["--tmr-settings-chat-inputs-height"] = Px(settings.ChatInputsHeight),
            ["--tmr-settings-streamlabs-panel-height"] = Px(settings.StreamlabsPanelHeight),
            ["--tmr-settings-region-segment-shell-height"] = Px(settings.RegionSegmentShellHeight),
            ["--tmr-settings-region-segment-gap"] = Px(settings.RegionSegmentGap),
            ["--tmr-settings-region-segment-padding"] = Px(settings.RegionSegmentPadding),
            ["--tmr-settings-region-segment-margin-bottom"] = Px(settings.RegionSegmentMarginBottom),
            ["--tmr-settings-region-tabs-crop-top-inset"] = Px(settings.RegionTabsCropTopInset),
            ["--tmr-settings-region-tabs-crop-extra-height"] = Px(settings.RegionTabsCropExtraHeight),
            ["--tmr-settings-region-segment-height"] = Px(settings.RegionSegmentHeight),
            ["--tmr-settings-region-segment-default-width"] = Px(settings.RegionSegmentDefaultWidth),
            ["--tmr-settings-region-segment-general-width"] = Px(settings.RegionSegmentGeneralWidth),
            ["--tmr-settings-region-segment-preview-width"] = Px(settings.RegionSegmentPreviewWidth),
            ["--tmr-settings-field-row-default-width"] = Px(settings.FieldRowDefaultWidth),
            ["--tmr-settings-field-row-height"] = Px(settings.FieldRowHeight),
            ["--tmr-settings-field-label-width"] = Px(settings.FieldLabelWidth),
            ["--tmr-settings-field-label-height"] = Px(settings.FieldLabelHeight),
            ["--tmr-settings-field-value-height"] = Px(settings.FieldValueHeight),
            ["--tmr-settings-preview-summary-text-top-offset"] = Px(settings.PreviewSummaryTextTopOffset),
            ["--tmr-settings-preview-summary-value-gap-x"] = Px(settings.PreviewSummaryValueGapX),
            ["--tmr-settings-preview-body-line-height"] = Px(settings.PreviewBodyLineHeight),
            ["--tmr-settings-preview-body-line-width"] = Px(settings.PreviewBodyLineWidth),
            ["--tmr-settings-support-raw-capture-label-width"] = Px(settings.SupportRawCaptureLabelWidth),
            ["--tmr-settings-support-description-offset-x"] = Px(settings.SupportDescriptionOffsetX),
            ["--tmr-settings-support-description-offset-y"] = Px(settings.SupportDescriptionOffsetY),
            ["--tmr-settings-support-description-width"] = Px(settings.SupportDescriptionWidth),
            ["--tmr-settings-support-description-line-height"] = Px(settings.SupportDescriptionLineHeight),
            ["--tmr-settings-support-description-line-stride"] = Px(settings.SupportDescriptionLineStride),
            ["--tmr-settings-toggle-width"] = Px(settings.ToggleWidth),
            ["--tmr-settings-toggle-height"] = Px(settings.ToggleHeight),
            ["--tmr-settings-slider-width"] = Px(settings.SliderWidth),
            ["--tmr-settings-slider-height"] = Px(settings.SliderHeight),
            ["--tmr-settings-stepper-width"] = Px(settings.StepperWidth),
            ["--tmr-settings-stepper-height"] = Px(settings.StepperHeight),
            ["--tmr-settings-segmented-width"] = Px(settings.SegmentedWidth),
            ["--tmr-settings-segmented-height"] = Px(settings.SegmentedHeight),
            ["--tmr-settings-segmented-padding"] = Px(settings.SegmentedPadding),
            ["--tmr-settings-segmented-choice-gap"] = Px(settings.SegmentedChoiceGap),
            ["--tmr-settings-wide-segmented-height"] = Px(settings.WideSegmentedHeight),
            ["--tmr-settings-provider-choice-width"] = Px(settings.ProviderChoiceWidth),
            ["--tmr-settings-streamlabs-input-width"] = Px(settings.StreamlabsInputWidth),
            ["--tmr-settings-streamlabs-input-height"] = Px(settings.StreamlabsInputHeight),
            ["--tmr-settings-twitch-input-width"] = Px(settings.TwitchInputWidth),
            ["--tmr-settings-copy-button-width"] = Px(settings.CopyButtonWidth),
            ["--tmr-settings-copy-button-height"] = Px(settings.CopyButtonHeight),
            ["--tmr-settings-support-bundle-value-width"] = Px(settings.SupportBundleValueWidth),
            ["--tmr-settings-support-bundle-value-top-offset"] = Px(settings.SupportBundleValueTopOffset),
            ["--tmr-settings-support-bundle-value-height-extra"] = Px(settings.SupportBundleValueHeightExtra),
            ["--tmr-settings-support-bundle-value-font-size"] = Px(settings.SupportBundleValueFontSize),
            ["--tmr-settings-field-label-font-size"] = Px(settings.FieldLabelFontSize),
            ["--tmr-settings-field-value-font-size"] = Px(settings.FieldValueFontSize),
            ["--tmr-settings-button-font-size"] = Px(settings.ButtonFontSize),
            ["--tmr-settings-segment-font-size"] = Px(settings.SegmentFontSize),
            ["--tmr-settings-segment-line-height"] = Px(settings.SegmentLineHeight),
            ["--tmr-settings-segment-padding-x"] = Px(settings.SegmentPaddingX),
            ["--tmr-settings-panel-title-font-size"] = Px(settings.PanelTitleFontSize),
            ["--tmr-settings-matrix-content-inset-x"] = Px(settings.MatrixContentInsetX),
            ["--tmr-settings-matrix-header-offset-y"] = Px(settings.MatrixHeaderOffsetY),
            ["--tmr-settings-matrix-first-row-offset-y"] = Px(settings.MatrixFirstRowOffsetY),
            ["--tmr-settings-matrix-header-height"] = Px(settings.MatrixHeaderHeight),
            ["--tmr-settings-matrix-row-height"] = Px(settings.MatrixRowHeight),
            ["--tmr-settings-matrix-row-gap"] = Px(settings.MatrixRowGap),
            ["--tmr-settings-matrix-panel-bottom-padding"] = Px(settings.MatrixPanelBottomPadding),
            ["--tmr-settings-matrix-column-gap"] = Px(settings.MatrixColumnGap),
            ["--tmr-settings-matrix-check-size"] = Px(settings.MatrixCheckSize),
            ["--tmr-settings-matrix-control-content-width"] = Px(settings.MatrixControlContentWidth),
            ["--tmr-settings-matrix-control-label-width"] = Px(settings.MatrixControlLabelWidth),
            ["--tmr-settings-matrix-control-gap"] = Px(settings.MatrixControlGap),
            ["--tmr-settings-matrix-control-cell-padding"] = Px(settings.MatrixControlCellPadding),
            ["--tmr-settings-matrix-control-stepper-width"] = Px(settings.MatrixControlStepperWidth),
            ["--tmr-settings-matrix-control-row-height"] = Px(settings.MatrixControlRowHeight),
            ["--tmr-settings-matrix-control-stepper-height"] = Px(settings.MatrixControlStepperHeight),
            ["--tmr-settings-block-grid-content-inset-x"] = Px(settings.BlockGridContentInsetX),
            ["--tmr-settings-block-grid-header-offset-y"] = Px(settings.BlockGridHeaderOffsetY),
            ["--tmr-settings-block-grid-first-row-offset-y"] = Px(settings.BlockGridFirstRowOffsetY),
            ["--tmr-settings-block-grid-panel-bottom-padding"] = Px(settings.BlockGridPanelBottomPadding),
            ["--tmr-settings-block-grid-column-gap"] = Px(settings.BlockGridColumnGap),
            ["--tmr-settings-block-grid-row-height"] = Px(settings.BlockGridRowHeight),
            ["--tmr-settings-block-grid-row-gap"] = Px(settings.BlockGridRowGap),
            ["--tmr-settings-block-grid-session-column-stride"] = Px(settings.BlockGridSessionColumnStride),
            ["--tmr-settings-block-grid-session-cells-right-inset"] = Px(settings.BlockGridSessionCellsRightInset),
            ["--tmr-settings-block-grid-visible-cell-right-inset"] = Px(settings.BlockGridVisibleCellRightInset),
            ["--tmr-settings-block-grid-check-size"] = Px(settings.BlockGridCheckSize),
            ["--tmr-settings-action-button-minimum-width"] = Px(settings.ActionButtonMinimumWidth),
            ["--tmr-settings-action-button-height"] = Px(settings.ActionButtonHeight),
            ["--tmr-settings-action-button-gap"] = Px(settings.ActionButtonGap),
            ["--tmr-settings-small-action-button-gap"] = Px(settings.SmallActionButtonGap),
            ["--tmr-settings-close-button-width"] = Px(settings.CloseButtonWidth),
            ["--tmr-settings-close-button-height"] = Px(settings.CloseButtonHeight),
            ["--tmr-settings-session-column-width"] = Px(settings.SessionColumnWidth),
            ["--tmr-settings-compact-session-column-width"] = Px(settings.CompactSessionColumnWidth),
            ["--tmr-settings-session-check-column-width"] = Px(settings.SessionCheckColumnWidth),
            ["--tmr-settings-session-check-column-gap"] = Px(settings.SessionCheckColumnGap),
            ["--tmr-settings-overlay-controls-panel-bottom-padding"] = Px(settings.OverlayControlsPanelBottomPadding)
        };
        AddCssVariablesFromProperties(variables, "tmr-overlay-sizes", overlaySizes);
        AddCssVariablesFromProperties(
            variables,
            "tmr-input-state",
            input,
            new HashSet<string>(StringComparer.Ordinal)
            {
                nameof(InputStateGeometryContract.RefreshIntervalMilliseconds),
                nameof(InputStateGeometryContract.MaximumTracePoints),
                nameof(InputStateGeometryContract.RailPreferredWidthFraction),
                nameof(InputStateGeometryContract.GraphGridLines)
            });
        AddCssVariablesFromProperties(
            variables,
            "tmr-flags",
            flags,
            new HashSet<string>(StringComparer.Ordinal)
            {
                nameof(FlagsGeometryContract.RefreshIntervalMilliseconds),
                nameof(FlagsGeometryContract.PoleInsetFractionX),
                nameof(FlagsGeometryContract.ClothAreaHeightFraction),
                nameof(FlagsGeometryContract.ClothWidthHeightFraction),
                nameof(FlagsGeometryContract.ClothTopFraction),
                nameof(FlagsGeometryContract.NativeLabelPointSize),
                nameof(FlagsGeometryContract.NativeCompactLabelPointSize),
                nameof(FlagsGeometryContract.CheckeredColumns),
                nameof(FlagsGeometryContract.CheckeredRows),
                nameof(FlagsGeometryContract.StripeWidthFraction),
                nameof(FlagsGeometryContract.CautionStripeStrideMultiplier),
                nameof(FlagsGeometryContract.DebrisStripeStrideMultiplier),
                nameof(FlagsGeometryContract.MeatballDiameterFraction),
                nameof(FlagsGeometryContract.PathControlOneFraction),
                nameof(FlagsGeometryContract.PathControlTwoFraction),
                nameof(FlagsGeometryContract.PathBottomWaveFraction),
                nameof(FlagsGeometryContract.GridTwoCountMaximum),
                nameof(FlagsGeometryContract.GridFourCountMaximum),
                nameof(FlagsGeometryContract.GridSixCountMaximum),
                nameof(FlagsGeometryContract.GridMaximumColumns)
            });
        AddCssVariablesFromProperties(
            variables,
            "tmr-canvas-overlays",
            canvas,
            new HashSet<string>(StringComparer.Ordinal)
            {
                nameof(CanvasOverlaysGeometryContract.GarageCoverAspectWidth),
                nameof(CanvasOverlaysGeometryContract.GarageCoverAspectHeight)
            });
        AddCssVariablesFromProperties(variables, "tmr-settings", settings);

        return string.Join(
            Environment.NewLine,
            variables.Select(variable => $"      {variable.Key}: {variable.Value};"));
    }

    private static string Px(float value)
    {
        return $"{value.ToString("0.###", CultureInfo.InvariantCulture)}px";
    }

    private static void AddCssVariablesFromProperties<T>(
        Dictionary<string, string> variables,
        string prefix,
        T source,
        IReadOnlySet<string>? unitlessProperties = null)
        where T : notnull
    {
        foreach (var property in typeof(T).GetProperties(BindingFlags.Instance | BindingFlags.Public))
        {
            if (property.GetValue(source) is int intValue)
            {
                variables[$"--{prefix}-{KebabCase(property.Name)}"] = unitlessProperties?.Contains(property.Name) == true
                    ? intValue.ToString(CultureInfo.InvariantCulture)
                    : Px(intValue);
            }
            else if (property.GetValue(source) is float floatValue)
            {
                variables[$"--{prefix}-{KebabCase(property.Name)}"] = unitlessProperties?.Contains(property.Name) == true
                    ? floatValue.ToString("0.###", CultureInfo.InvariantCulture)
                    : Px(floatValue);
            }
        }
    }

    private static string KebabCase(string value)
    {
        var builder = new System.Text.StringBuilder(value.Length + 8);
        for (var index = 0; index < value.Length; index++)
        {
            var current = value[index];
            if (char.IsUpper(current))
            {
                if (index > 0)
                {
                    builder.Append('-');
                }

                builder.Append(char.ToLowerInvariant(current));
            }
            else
            {
                builder.Append(current);
            }
        }

        return builder.ToString();
    }
}

internal sealed record OverlayGeometryContract(
    GapGraphGeometryContract GapGraph,
    MetricRowsGeometryContract MetricRows,
    StreamChatGeometryContract StreamChat,
    InputStateGeometryContract InputState,
    FlagsGeometryContract Flags,
    CanvasOverlaysGeometryContract CanvasOverlays,
    SettingsGeometryContract SettingsGeometry,
    OverlaySizesGeometryContract OverlaySizes,
    TableGeometryContract TableGeometry);

internal sealed record GapGraphGeometryContract(
    float FrameInsetX,
    float FrameInsetY,
    float AxisWidth,
    float XAxisHeight,
    float EndpointLabelLaneWidth,
    float MetricsTableWidth,
    float MetricsTableGap,
    float MetricsMinimumPlotWidth,
    float MetricsMinimumTableHeight,
    float MetricsTableInset,
    float MetricsRowsTopOffset,
    float MetricsBottomPadding,
    float MetricsColumnGap,
    float MetricsRowMinHeight,
    float MetricsRowMaxHeight,
    bool MetricOnlyUsesFullFrame,
    float BrowserPanelPaddingX,
    float BrowserPanelPaddingY);

internal sealed record MetricRowsGeometryContract(
    int MinimumSimpleTelemetryHeight,
    int MinimumSimpleTelemetryWidth,
    int NonRaceSimpleTelemetryHeightReduction,
    int PitServiceMetricOnlyWidth,
    int MinimumFuelCalculatorHeight,
    int FuelNonRaceHeight,
    int MinimumChromeAdjustedHeight,
    int HeaderChromeHeight,
    int FooterChromeHeight,
    int BodyGap,
    int ContentPaddingX,
    int ContentPaddingTop,
    int ContentPaddingBottom,
    int CollapsedFooterReserveHeight,
    int FuelContentVerticalPadding,
    int FuelSectionTitleReserveHeight,
    float PlainRowHeight,
    float SegmentedRowHeight,
    float DirectionalRowHeight,
    float RowGap,
    float SectionTitleHeight,
    float SectionTitleBottomGap,
    float SectionTitleInsetX,
    float SectionGap,
    float MetricListMinimumWidth,
    float RowRadius,
    float RowBorderWidth,
    float LabelColumnWidth,
    float LabelPaddingLeft,
    float LabelPaddingRight,
    float ValuePaddingLeft,
    float ValuePaddingRight,
    float ValueDividerWidth,
    float CellVerticalPadding,
    float ValueSegmentGap,
    float PitServiceSectionGap,
    float PitServiceContentChromeHeight,
    float MetricGridMinimumHeight,
    float MetricGridGap,
    float MetricGridTopReserve,
    float MetricGridBottomReserve,
    float MetricGridTitleHeight,
    float MetricGridTitleBottomGap,
    float MetricGridHeaderHeight,
    float MetricGridHeaderBottomGap,
    float MetricGridRowHeight,
    float MetricGridRowGap,
    float MetricGridCellInset,
    float MetricGridCellGap,
    float MetricGridCellMinimumWidth,
    float MetricGridCellHeight);

internal sealed record StreamChatGeometryContract(
    float OverlayWidth,
    float OverlayHeight,
    float HeaderHeight,
    float HeaderRightReserve,
    float CloseButtonSize,
    float CloseButtonRight,
    float CloseButtonTop,
    float ContentHorizontalPadding,
    float ContentTopPadding,
    float ContentBottomPadding,
    float RowGap,
    float RowMinHeight,
    float RowPaddingX,
    float RowPaddingY,
    float RowBorderWidth,
    float RowRadius,
    float HeadGap,
    float HeadHeight,
    float HeadTextGap,
    float BadgeGap,
    float BadgeMaxRowFraction,
    float BadgeMinWidth,
    float BadgeMaxWidth,
    float BadgeHeight,
    float BadgePaddingX,
    float BadgeImageSize,
    float NameFontSize,
    float NameFontPointSize,
    float NameFontWeight,
    float ChipGap,
    float ChipMaxWidth,
    float ChipHeight,
    float ChipPaddingX,
    float ChipRadius,
    float ChipFontSize,
    float TextFontSize,
    float TextFontPointSize,
    float TextLineHeight,
    float EmoteSize,
    float EmoteMarginTop,
    float EmoteMarginX,
    float EmoteMarginBottom,
    float AvailableHeightFallbackOffset,
    float MinimumAvailableHeight,
    int MaxRows,
    float RowBudget);

internal sealed record InputStateGeometryContract(
    int RefreshIntervalMilliseconds,
    int MaximumTracePoints,
    int GraphOnlyBaseWidth,
    int RailOnlyBaseWidth,
    int CompactWidth,
    int CompactHeight,
    int CompactMaxWidth,
    int CompactMaxHeight,
    int ContentPaddingX,
    int ContentPaddingTop,
    int ContentPaddingBottom,
    int HeaderBandHeight,
    int CompactContentPaddingX,
    int CompactContentPaddingTop,
    int CompactContentPaddingBottom,
    int CompactHeaderBandHeight,
    int GraphMinimumWidth,
    int GraphNoRailMinimumWidth,
    int GraphRailGap,
    int CompactGraphMinimumWidth,
    int CompactRailMinimumWidth,
    int CompactGraphRailGap,
    int RailMinimumWidth,
    int RailPreferredMinimumWidth,
    float RailPreferredWidthFraction,
    int RailMaximumWidth,
    int RailOnlyMaximumWidth,
    int RailPadding,
    int CompactRailPadding,
    int RailGap,
    int CompactRailGap,
    int BarsGap,
    int CompactBarsGap,
    int ReadoutsGap,
    int CompactReadoutsGap,
    int RailLabelColumnWidth,
    int CompactRailLabelColumnWidth,
    int RailColumnGap,
    int CompactRailColumnGap,
    int BarHeight,
    int CompactBarHeight,
    int BarTrackHeight,
    int CompactBarTrackHeight,
    int ReadoutHeight,
    int CompactReadoutHeight,
    int WheelHeaderHeight,
    int CompactWheelHeaderHeight,
    int WheelGap,
    int CompactWheelGap,
    int WheelMinimumHeight,
    int CompactWheelMinimumHeight,
    int WheelMaximumHeight,
    int CompactWheelMaximumHeight,
    int WheelSvgSize,
    int CompactWheelSvgSize,
    int GraphGridLines,
    int CompactRailHeightThreshold,
    int RailContentCompactHeightThreshold);

internal sealed record FlagsGeometryContract(
    int RefreshIntervalMilliseconds,
    int MinimumWidth,
    int MinimumHeight,
    int MaximumWidth,
    int MaximumHeight,
    int OuterPadding,
    int CellGap,
    int CompactCellHeightThreshold,
    int CompactCellWidthThreshold,
    int LabelHeight,
    int CompactLabelHeight,
    int LabelInsetX,
    int LabelBottomInset,
    int FlagAreaMinimumHeight,
    int PoleMinimumInsetX,
    float PoleInsetFractionX,
    int PoleTopOffset,
    int PoleBottomInset,
    int PoleShadowOffset,
    int PoleCompactStrokeWidth,
    int PoleStrokeWidth,
    int ClothLeftOffset,
    int ClothRightInset,
    int ClothMinimumWidth,
    int ClothMinimumHeight,
    float ClothAreaHeightFraction,
    float ClothWidthHeightFraction,
    float ClothTopFraction,
    int ClothTopMinimum,
    float CompactWave,
    float Wave,
    int LabelFontSize,
    int CompactLabelFontSize,
    float NativeLabelPointSize,
    float NativeCompactLabelPointSize,
    int CheckeredColumns,
    int CheckeredRows,
    int StripeMinimumWidth,
    float StripeWidthFraction,
    float CautionStripeStrideMultiplier,
    float DebrisStripeStrideMultiplier,
    float MeatballDiameterFraction,
    float PathControlOneFraction,
    float PathControlTwoFraction,
    float PathBottomWaveFraction,
    int GridTwoCountMaximum,
    int GridFourCountMaximum,
    int GridSixCountMaximum,
    int GridMaximumColumns);

internal sealed record CanvasOverlaysGeometryContract(
    int TrackMapWidth,
    int TrackMapHeight,
    int CarRadarWidth,
    int CarRadarHeight,
    int GarageCoverWidth,
    int GarageCoverHeight,
    int GarageCoverAspectWidth,
    int GarageCoverAspectHeight,
    bool GarageCoverBrowserOnly,
    bool UseConfiguredCanvasBacking,
    bool CoverImageObjectFitCover);

internal sealed record SettingsGeometryContract(
    int DesignWidth,
    int DesignHeight,
    int NativeCanvasOffsetX,
    int NativeCanvasOffsetY,
    int ShellWidth,
    int ShellHeight,
    int ShellCornerRadius,
    int TitlebarHeight,
    int BodyHeight,
    int SidebarX,
    int SidebarY,
    int SidebarWidth,
    int SidebarHeight,
    int ContentX,
    int ContentY,
    int ContentWidth,
    int ContentHeight,
    int ContentHeaderHeight,
    int ContentBodyY,
    int ContentBodyHeight,
    int ContentBodyPaddingTop,
    int ContentBodyWithRegionsPaddingTop,
    int ContentBodyPaddingX,
    int ContentBodyPaddingBottom,
    int PanelX,
    int PanelNoRegionsY,
    int PanelWithRegionsY,
    int PanelSmallWidth,
    int PanelMediumWidth,
    int PanelWideWidth,
    int PanelBorderWidth,
    int PanelPaddingX,
    int PanelPaddingY,
    int PanelTitleHeight,
    int PanelTitleBoundsHeight,
    int PanelTitlePaddingBottom,
    int PanelTitleMarginBottom,
    int GeneralGridGap,
    int GeneralTopGridHeight,
    int UnitsPanelWidth,
    int UnitsPanelHeight,
    int UpdatesPanelWidth,
    int UpdatesPanelHeight,
    int NativeUpdatesPanelHeight,
    int PreviewPanelWidth,
    int PreviewPanelHeight,
    int PreviewPanelMarginTop,
    int SupportPanelHeight,
    int SupportBridgeColumnWidth,
    int SupportBridgeColumnGap,
    int SupportBridgeRowHeight,
    int SupportBridgeRowStride,
    int SupportBridgeLabelWidth,
    int SupportBridgeValueWidth,
    int SupportBridgeErrorRowOffsetY,
    int SupportBridgeDescriptionOffsetY,
    int SupportBridgeDescriptionLineHeight,
    int SupportBridgeDescriptionLineStride,
    int OverlayControlsPanelHeight,
    int GarageOverlayControlsPanelHeight,
    int BrowserSourcePanelWidth,
    int BrowserSourcePanelHeight,
    int BrowserSourceUrlHeight,
    int BrowserSourceSizeGapY,
    int BrowserSourceSizeHeight,
    int BrowserSourceCopyButtonTop,
    int BrowserSourceCopyButtonRight,
    int ContentMatrixWidth,
    int ContentMatrixMinimumHeight,
    int ContentMatrixPreviewHeight,
    int ChatInputsWidth,
    int ChatInputsHeight,
    int StreamlabsPanelHeight,
    int RegionSegmentShellHeight,
    int RegionSegmentGap,
    int RegionSegmentPadding,
    int RegionSegmentMarginBottom,
    int RegionTabsCropTopInset,
    int RegionTabsCropExtraHeight,
    int RegionSegmentHeight,
    int RegionSegmentDefaultWidth,
    int RegionSegmentGeneralWidth,
    int RegionSegmentPreviewWidth,
    int RegionSegmentStreamlabsWidth,
    int SidebarTabX,
    int SidebarTabY,
    int SidebarTabWidth,
    int SidebarTabHeight,
    int SidebarTabStride,
    int CloseButtonX,
    int CloseButtonY,
    int FieldRowDefaultWidth,
    int FieldRowHeight,
    int FieldRowOffsetY,
    int FieldRowStride,
    int FieldLabelTopOffset,
    int FieldControlTopOffset,
    int FieldStepperTopOffset,
    int FieldValueTopOffset,
    int FieldLabelWidth,
    int FieldLabelHeight,
    int FieldValueHeight,
    int PreviewSummaryOffsetY,
    int PreviewSummaryHeight,
    int PreviewSummaryTextTopOffset,
    int PreviewSummaryValueGapX,
    int PreviewModeOffsetY,
    int PreviewBodyTextOffsetY,
    int PreviewBodyLineStride,
    int PreviewBodyLineHeight,
    int PreviewBodyLineWidth,
    int UpdatesActionButtonGapY,
    int SupportRawCaptureLabelWidth,
    int SupportButtonRowGapY,
    int SupportDescriptionOffsetX,
    int SupportDescriptionOffsetY,
    int SupportDescriptionWidth,
    int SupportDescriptionLineHeight,
    int SupportDescriptionLineStride,
    int SupportStatusX,
    int SupportStatusY,
    int SupportStatusWidth,
    int SupportAnalysisRowHeight,
    int SupportAnalysisRowStride,
    int SupportAnalysisLabelTopOffset,
    int SupportAnalysisLabelWidth,
    int SupportAnalysisLabelHeight,
    int SupportAnalysisValueTopOffset,
    int SupportAnalysisValueWidth,
    int SupportAnalysisValueHeight,
    int SupportAnalysisToggleTopOffset,
    int GaragePreviewStageHeight,
    int GaragePreviewImageWidth,
    int GaragePreviewImageHeight,
    int ToggleRowWidth,
    int SliderRowWidth,
    int StepperRowWidth,
    int SegmentedRowWidth,
    int ProviderChoiceRowWidth,
    int StreamlabsUrlRowWidth,
    int TwitchChannelRowWidth,
    int ToggleWidth,
    int ToggleHeight,
    int SliderWidth,
    int SliderHeight,
    int StepperWidth,
    int StepperHeight,
    int StepperButtonWidth,
    int StepperButtonHeight,
    int StepperGap,
    int SegmentedWidth,
    int SegmentedHeight,
    int SegmentedPadding,
    int SegmentedChoiceGap,
    int WideSegmentedWidth,
    int WideSegmentedHeight,
    int WideSegmentedColumnWidth,
    int ProviderChoiceWidth,
    int StreamlabsInputWidth,
    int StreamlabsInputHeight,
    int TwitchInputWidth,
    int CopyButtonWidth,
    int CopyButtonHeight,
    int SupportBundleRowX,
    int SupportBundleRowY,
    int SupportBundleRowWidth,
    int SupportBundleRowHeight,
    int SupportBundleLabelWidth,
    int SupportBundleLabelHeight,
    int SupportBundleValueX,
    int SupportBundleValueY,
    int SupportBundleValueWidth,
    int SupportBundleValueHeight,
    int SupportBundleValueTopOffset,
    int SupportBundleValueHeightExtra,
    float SupportBundleValueFontSize,
    int FieldLabelFontSize,
    int FieldValueFontSize,
    int ButtonFontSize,
    int SegmentFontSize,
    int SegmentLineHeight,
    int SegmentPaddingX,
    int PanelTitleFontSize,
    int NativePanelTitleFontSize,
    int MatrixContentInsetX,
    int MatrixHeaderOffsetY,
    int MatrixFirstRowOffsetY,
    int MatrixHeaderHeight,
    int MatrixRowHeight,
    int MatrixRowGap,
    int MatrixPanelBottomPadding,
    int MatrixColumnGap,
    int MatrixCheckSize,
    int CheckSize,
    int MatrixControlContentWidth,
    int MatrixControlLabelWidth,
    int MatrixControlGap,
    int MatrixControlItemGap,
    int MatrixControlCellPadding,
    int MatrixControlStepperWidth,
    int MatrixControlStepperButtonWidth,
    int MatrixControlRowTopGap,
    int MatrixControlRowHeight,
    int MatrixControlHeight,
    int MatrixControlStepperHeight,
    int MatrixHeadHeight,
    int BlockGridContentInsetX,
    int BlockGridHeaderOffsetY,
    int BlockGridFirstRowOffsetY,
    int BlockGridPanelBottomPadding,
    int BlockGridColumnGap,
    int BlockGridRowHeight,
    int BlockGridRowGap,
    int BlockGridSessionColumnStride,
    int BlockGridSessionCellsRightInset,
    int BlockGridVisibleCellRightInset,
    int BlockGridCheckSize,
    int CompactMatrixRowGap,
    int CompactMatrixColumnGap,
    int CompactMatrixPaddingY,
    int CompactMatrixPaddingX,
    int CompactMatrixHeadingHeight,
    int CompactMatrixHeadingPaddingBottom,
    int CompactMatrixHeadingMarginBottom,
    int CompactMatrixLegendGap,
    int CompactMatrixRowHeight,
    int ActionButtonMinimumWidth,
    int ActionButtonHeight,
    int ActionButtonGap,
    int SmallActionButtonGap,
    int CloseButtonWidth,
    int CloseButtonHeight,
    int UpdateCheckButtonWidth,
    int UpdatePrimaryButtonWidth,
    int SupportCreateBundleButtonWidth,
    int SupportOpenBundleButtonWidth,
    int GarageImportButtonWidth,
    int GarageClearButtonWidth,
    int StreamChatSaveButtonWidth,
    int SessionColumnWidth,
    int CompactSessionColumnWidth,
    int SessionCheckColumnWidth,
    int SessionCheckColumnGap,
    int OverlayControlsPanelBottomPadding);

internal sealed record OverlaySizesGeometryContract(
    int StandingsWidth,
    int StandingsBrowserReviewWidth,
    int StandingsHeight,
    int RelativeWidth,
    int RelativeHeight,
    int GapToLeaderWidth,
    int GapToLeaderHeight,
    int GapToLeaderMinimumWidth,
    int GapToLeaderGraphOnlyWidth,
    int GapToLeaderTrendOnlyWidth,
    int GapToLeaderMinimumHeight,
    int RelativeHeaderChromeCollapseHeight,
    int TrackMapWidth,
    int TrackMapHeight,
    int StreamChatWidth,
    int StreamChatHeight,
    int GarageCoverWidth,
    int GarageCoverHeight,
    int FuelCalculatorWidth,
    int FuelCalculatorHeight,
    int InputStateWidth,
    int InputStateHeight,
    int CarRadarWidth,
    int CarRadarHeight,
    int FlagsWidth,
    int FlagsHeight,
    int SessionWeatherWidth,
    int SessionWeatherHeight,
    int PitServiceWidth,
    int PitServiceHeight);

internal sealed record TableGeometryContract(
    int BrowserWidthPadding,
    int StandingsClassPositionWidth,
    int StandingsCarNumberWidth,
    int StandingsDriverWidth,
    int StandingsClassGapWidth,
    int StandingsPreviousIntervalWidth,
    int StandingsFastestLapWidth,
    int StandingsLastLapWidth,
    int StandingsPitStatusWidth,
    int RelativePositionWidth,
    int RelativeDriverWidth,
    int RelativeDeltaWidth,
    int RelativePitStatusWidth,
    int RelativeMinimumHeight,
    int RelativeHeightChrome,
    int RelativeRowHeight,
    int RelativeRowGap);
