// <auto-generated />
// Generated by tools/generate_overlay_geometry_constants.py from
// src/TmrOverlay.App/Overlays/BrowserSources/Assets/contracts/overlay-geometry.json.
// Do not edit manually.

namespace TmrOverlay.App.Overlays;

internal static class OverlayGeometryContractValues
{
    public static OverlayGeometryContract Current { get; } = new(
        GapGraph: new GapGraphGeometryContract(
            FrameInsetX: GapGraph.FrameInsetX,
            FrameInsetY: GapGraph.FrameInsetY,
            AxisWidth: GapGraph.AxisWidth,
            XAxisHeight: GapGraph.XAxisHeight,
            EndpointLabelLaneWidth: GapGraph.EndpointLabelLaneWidth,
            MetricsTableWidth: GapGraph.MetricsTableWidth,
            MetricsTableGap: GapGraph.MetricsTableGap,
            MetricsMinimumPlotWidth: GapGraph.MetricsMinimumPlotWidth,
            MetricsMinimumTableHeight: GapGraph.MetricsMinimumTableHeight,
            MetricsTableInset: GapGraph.MetricsTableInset,
            MetricsRowsTopOffset: GapGraph.MetricsRowsTopOffset,
            MetricsBottomPadding: GapGraph.MetricsBottomPadding,
            MetricsColumnGap: GapGraph.MetricsColumnGap,
            MetricsRowMinHeight: GapGraph.MetricsRowMinHeight,
            MetricsRowMaxHeight: GapGraph.MetricsRowMaxHeight,
            MetricOnlyUsesFullFrame: GapGraph.MetricOnlyUsesFullFrame,
            BrowserPanelPaddingX: GapGraph.BrowserPanelPaddingX,
            BrowserPanelPaddingY: GapGraph.BrowserPanelPaddingY),
        MetricRows: new MetricRowsGeometryContract(
            MinimumSimpleTelemetryHeight: MetricRows.MinimumSimpleTelemetryHeight,
            MinimumSimpleTelemetryWidth: MetricRows.MinimumSimpleTelemetryWidth,
            NonRaceSimpleTelemetryHeightReduction: MetricRows.NonRaceSimpleTelemetryHeightReduction,
            PitServiceMetricOnlyWidth: MetricRows.PitServiceMetricOnlyWidth,
            MinimumFuelCalculatorHeight: MetricRows.MinimumFuelCalculatorHeight,
            FuelNonRaceHeight: MetricRows.FuelNonRaceHeight,
            MinimumChromeAdjustedHeight: MetricRows.MinimumChromeAdjustedHeight,
            HeaderChromeHeight: MetricRows.HeaderChromeHeight,
            FooterChromeHeight: MetricRows.FooterChromeHeight,
            BodyGap: MetricRows.BodyGap,
            ContentPaddingX: MetricRows.ContentPaddingX,
            ContentPaddingTop: MetricRows.ContentPaddingTop,
            ContentPaddingBottom: MetricRows.ContentPaddingBottom,
            CollapsedFooterReserveHeight: MetricRows.CollapsedFooterReserveHeight,
            FuelContentVerticalPadding: MetricRows.FuelContentVerticalPadding,
            FuelSectionTitleReserveHeight: MetricRows.FuelSectionTitleReserveHeight,
            PlainRowHeight: MetricRows.PlainRowHeight,
            SegmentedRowHeight: MetricRows.SegmentedRowHeight,
            DirectionalRowHeight: MetricRows.DirectionalRowHeight,
            RowGap: MetricRows.RowGap,
            SectionTitleHeight: MetricRows.SectionTitleHeight,
            SectionTitleBottomGap: MetricRows.SectionTitleBottomGap,
            SectionTitleInsetX: MetricRows.SectionTitleInsetX,
            SectionGap: MetricRows.SectionGap,
            MetricListMinimumWidth: MetricRows.MetricListMinimumWidth,
            RowRadius: MetricRows.RowRadius,
            RowBorderWidth: MetricRows.RowBorderWidth,
            LabelColumnWidth: MetricRows.LabelColumnWidth,
            LabelPaddingLeft: MetricRows.LabelPaddingLeft,
            LabelPaddingRight: MetricRows.LabelPaddingRight,
            ValuePaddingLeft: MetricRows.ValuePaddingLeft,
            ValuePaddingRight: MetricRows.ValuePaddingRight,
            ValueDividerWidth: MetricRows.ValueDividerWidth,
            CellVerticalPadding: MetricRows.CellVerticalPadding,
            ValueSegmentGap: MetricRows.ValueSegmentGap,
            PitServiceSectionGap: MetricRows.PitServiceSectionGap,
            PitServiceContentChromeHeight: MetricRows.PitServiceContentChromeHeight,
            MetricGridMinimumHeight: MetricRows.MetricGridMinimumHeight,
            MetricGridGap: MetricRows.MetricGridGap,
            MetricGridTopReserve: MetricRows.MetricGridTopReserve,
            MetricGridBottomReserve: MetricRows.MetricGridBottomReserve,
            MetricGridTitleHeight: MetricRows.MetricGridTitleHeight,
            MetricGridTitleBottomGap: MetricRows.MetricGridTitleBottomGap,
            MetricGridHeaderHeight: MetricRows.MetricGridHeaderHeight,
            MetricGridHeaderBottomGap: MetricRows.MetricGridHeaderBottomGap,
            MetricGridRowHeight: MetricRows.MetricGridRowHeight,
            MetricGridRowGap: MetricRows.MetricGridRowGap,
            MetricGridCellInset: MetricRows.MetricGridCellInset,
            MetricGridCellGap: MetricRows.MetricGridCellGap,
            MetricGridCellMinimumWidth: MetricRows.MetricGridCellMinimumWidth,
            MetricGridCellHeight: MetricRows.MetricGridCellHeight),
        StreamChat: new StreamChatGeometryContract(
            OverlayWidth: StreamChat.OverlayWidth,
            OverlayHeight: StreamChat.OverlayHeight,
            HeaderHeight: StreamChat.HeaderHeight,
            HeaderRightReserve: StreamChat.HeaderRightReserve,
            CloseButtonSize: StreamChat.CloseButtonSize,
            CloseButtonRight: StreamChat.CloseButtonRight,
            CloseButtonTop: StreamChat.CloseButtonTop,
            ContentHorizontalPadding: StreamChat.ContentHorizontalPadding,
            ContentTopPadding: StreamChat.ContentTopPadding,
            ContentBottomPadding: StreamChat.ContentBottomPadding,
            RowGap: StreamChat.RowGap,
            RowMinHeight: StreamChat.RowMinHeight,
            RowPaddingX: StreamChat.RowPaddingX,
            RowPaddingY: StreamChat.RowPaddingY,
            RowBorderWidth: StreamChat.RowBorderWidth,
            RowRadius: StreamChat.RowRadius,
            HeadGap: StreamChat.HeadGap,
            HeadHeight: StreamChat.HeadHeight,
            HeadTextGap: StreamChat.HeadTextGap,
            BadgeGap: StreamChat.BadgeGap,
            BadgeMaxRowFraction: StreamChat.BadgeMaxRowFraction,
            BadgeMinWidth: StreamChat.BadgeMinWidth,
            BadgeMaxWidth: StreamChat.BadgeMaxWidth,
            BadgeHeight: StreamChat.BadgeHeight,
            BadgePaddingX: StreamChat.BadgePaddingX,
            BadgeImageSize: StreamChat.BadgeImageSize,
            NameFontSize: StreamChat.NameFontSize,
            NameFontPointSize: StreamChat.NameFontPointSize,
            NameFontWeight: StreamChat.NameFontWeight,
            ChipGap: StreamChat.ChipGap,
            ChipMaxWidth: StreamChat.ChipMaxWidth,
            ChipHeight: StreamChat.ChipHeight,
            ChipPaddingX: StreamChat.ChipPaddingX,
            ChipRadius: StreamChat.ChipRadius,
            ChipFontSize: StreamChat.ChipFontSize,
            TextFontSize: StreamChat.TextFontSize,
            TextFontPointSize: StreamChat.TextFontPointSize,
            TextLineHeight: StreamChat.TextLineHeight,
            EmoteSize: StreamChat.EmoteSize,
            EmoteMarginTop: StreamChat.EmoteMarginTop,
            EmoteMarginX: StreamChat.EmoteMarginX,
            EmoteMarginBottom: StreamChat.EmoteMarginBottom,
            AvailableHeightFallbackOffset: StreamChat.AvailableHeightFallbackOffset,
            MinimumAvailableHeight: StreamChat.MinimumAvailableHeight,
            MaxRows: StreamChat.MaxRows,
            RowBudget: StreamChat.RowBudget),
        InputState: new InputStateGeometryContract(
            RefreshIntervalMilliseconds: InputState.RefreshIntervalMilliseconds,
            MaximumTracePoints: InputState.MaximumTracePoints,
            GraphOnlyBaseWidth: InputState.GraphOnlyBaseWidth,
            RailOnlyBaseWidth: InputState.RailOnlyBaseWidth,
            CompactWidth: InputState.CompactWidth,
            CompactHeight: InputState.CompactHeight,
            CompactMaxWidth: InputState.CompactMaxWidth,
            CompactMaxHeight: InputState.CompactMaxHeight,
            ContentPaddingX: InputState.ContentPaddingX,
            ContentPaddingTop: InputState.ContentPaddingTop,
            ContentPaddingBottom: InputState.ContentPaddingBottom,
            HeaderBandHeight: InputState.HeaderBandHeight,
            CompactContentPaddingX: InputState.CompactContentPaddingX,
            CompactContentPaddingTop: InputState.CompactContentPaddingTop,
            CompactContentPaddingBottom: InputState.CompactContentPaddingBottom,
            CompactHeaderBandHeight: InputState.CompactHeaderBandHeight,
            GraphMinimumWidth: InputState.GraphMinimumWidth,
            GraphNoRailMinimumWidth: InputState.GraphNoRailMinimumWidth,
            GraphRailGap: InputState.GraphRailGap,
            CompactGraphMinimumWidth: InputState.CompactGraphMinimumWidth,
            CompactRailMinimumWidth: InputState.CompactRailMinimumWidth,
            CompactGraphRailGap: InputState.CompactGraphRailGap,
            RailMinimumWidth: InputState.RailMinimumWidth,
            RailPreferredMinimumWidth: InputState.RailPreferredMinimumWidth,
            RailPreferredWidthFraction: InputState.RailPreferredWidthFraction,
            RailMaximumWidth: InputState.RailMaximumWidth,
            RailOnlyMaximumWidth: InputState.RailOnlyMaximumWidth,
            RailPadding: InputState.RailPadding,
            CompactRailPadding: InputState.CompactRailPadding,
            RailGap: InputState.RailGap,
            CompactRailGap: InputState.CompactRailGap,
            BarsGap: InputState.BarsGap,
            CompactBarsGap: InputState.CompactBarsGap,
            ReadoutsGap: InputState.ReadoutsGap,
            CompactReadoutsGap: InputState.CompactReadoutsGap,
            RailLabelColumnWidth: InputState.RailLabelColumnWidth,
            CompactRailLabelColumnWidth: InputState.CompactRailLabelColumnWidth,
            RailColumnGap: InputState.RailColumnGap,
            CompactRailColumnGap: InputState.CompactRailColumnGap,
            BarHeight: InputState.BarHeight,
            CompactBarHeight: InputState.CompactBarHeight,
            BarTrackHeight: InputState.BarTrackHeight,
            CompactBarTrackHeight: InputState.CompactBarTrackHeight,
            ReadoutHeight: InputState.ReadoutHeight,
            CompactReadoutHeight: InputState.CompactReadoutHeight,
            WheelHeaderHeight: InputState.WheelHeaderHeight,
            CompactWheelHeaderHeight: InputState.CompactWheelHeaderHeight,
            WheelGap: InputState.WheelGap,
            CompactWheelGap: InputState.CompactWheelGap,
            WheelMinimumHeight: InputState.WheelMinimumHeight,
            CompactWheelMinimumHeight: InputState.CompactWheelMinimumHeight,
            WheelMaximumHeight: InputState.WheelMaximumHeight,
            CompactWheelMaximumHeight: InputState.CompactWheelMaximumHeight,
            WheelSvgSize: InputState.WheelSvgSize,
            CompactWheelSvgSize: InputState.CompactWheelSvgSize,
            GraphGridLines: InputState.GraphGridLines,
            CompactRailHeightThreshold: InputState.CompactRailHeightThreshold,
            RailContentCompactHeightThreshold: InputState.RailContentCompactHeightThreshold),
        Flags: new FlagsGeometryContract(
            RefreshIntervalMilliseconds: Flags.RefreshIntervalMilliseconds,
            MinimumWidth: Flags.MinimumWidth,
            MinimumHeight: Flags.MinimumHeight,
            MaximumWidth: Flags.MaximumWidth,
            MaximumHeight: Flags.MaximumHeight,
            OuterPadding: Flags.OuterPadding,
            CellGap: Flags.CellGap,
            CompactCellHeightThreshold: Flags.CompactCellHeightThreshold,
            CompactCellWidthThreshold: Flags.CompactCellWidthThreshold,
            LabelHeight: Flags.LabelHeight,
            CompactLabelHeight: Flags.CompactLabelHeight,
            LabelInsetX: Flags.LabelInsetX,
            LabelBottomInset: Flags.LabelBottomInset,
            FlagAreaMinimumHeight: Flags.FlagAreaMinimumHeight,
            PoleMinimumInsetX: Flags.PoleMinimumInsetX,
            PoleInsetFractionX: Flags.PoleInsetFractionX,
            PoleTopOffset: Flags.PoleTopOffset,
            PoleBottomInset: Flags.PoleBottomInset,
            PoleShadowOffset: Flags.PoleShadowOffset,
            PoleCompactStrokeWidth: Flags.PoleCompactStrokeWidth,
            PoleStrokeWidth: Flags.PoleStrokeWidth,
            ClothLeftOffset: Flags.ClothLeftOffset,
            ClothRightInset: Flags.ClothRightInset,
            ClothMinimumWidth: Flags.ClothMinimumWidth,
            ClothMinimumHeight: Flags.ClothMinimumHeight,
            ClothAreaHeightFraction: Flags.ClothAreaHeightFraction,
            ClothWidthHeightFraction: Flags.ClothWidthHeightFraction,
            ClothTopFraction: Flags.ClothTopFraction,
            ClothTopMinimum: Flags.ClothTopMinimum,
            CompactWave: Flags.CompactWave,
            Wave: Flags.Wave,
            LabelFontSize: Flags.LabelFontSize,
            CompactLabelFontSize: Flags.CompactLabelFontSize,
            NativeLabelPointSize: Flags.NativeLabelPointSize,
            NativeCompactLabelPointSize: Flags.NativeCompactLabelPointSize,
            CheckeredColumns: Flags.CheckeredColumns,
            CheckeredRows: Flags.CheckeredRows,
            StripeMinimumWidth: Flags.StripeMinimumWidth,
            StripeWidthFraction: Flags.StripeWidthFraction,
            CautionStripeStrideMultiplier: Flags.CautionStripeStrideMultiplier,
            DebrisStripeStrideMultiplier: Flags.DebrisStripeStrideMultiplier,
            MeatballDiameterFraction: Flags.MeatballDiameterFraction,
            PathControlOneFraction: Flags.PathControlOneFraction,
            PathControlTwoFraction: Flags.PathControlTwoFraction,
            PathBottomWaveFraction: Flags.PathBottomWaveFraction,
            GridTwoCountMaximum: Flags.GridTwoCountMaximum,
            GridFourCountMaximum: Flags.GridFourCountMaximum,
            GridSixCountMaximum: Flags.GridSixCountMaximum,
            GridMaximumColumns: Flags.GridMaximumColumns),
        CanvasOverlays: new CanvasOverlaysGeometryContract(
            TrackMapWidth: CanvasOverlays.TrackMapWidth,
            TrackMapHeight: CanvasOverlays.TrackMapHeight,
            CarRadarWidth: CanvasOverlays.CarRadarWidth,
            CarRadarHeight: CanvasOverlays.CarRadarHeight,
            GarageCoverWidth: CanvasOverlays.GarageCoverWidth,
            GarageCoverHeight: CanvasOverlays.GarageCoverHeight,
            GarageCoverAspectWidth: CanvasOverlays.GarageCoverAspectWidth,
            GarageCoverAspectHeight: CanvasOverlays.GarageCoverAspectHeight,
            GarageCoverBrowserOnly: CanvasOverlays.GarageCoverBrowserOnly,
            UseConfiguredCanvasBacking: CanvasOverlays.UseConfiguredCanvasBacking,
            CoverImageObjectFitCover: CanvasOverlays.CoverImageObjectFitCover),
        SettingsGeometry: new SettingsGeometryContract(
            DesignWidth: SettingsGeometry.DesignWidth,
            DesignHeight: SettingsGeometry.DesignHeight,
            NativeCanvasOffsetX: SettingsGeometry.NativeCanvasOffsetX,
            NativeCanvasOffsetY: SettingsGeometry.NativeCanvasOffsetY,
            ShellWidth: SettingsGeometry.ShellWidth,
            ShellHeight: SettingsGeometry.ShellHeight,
            ShellCornerRadius: SettingsGeometry.ShellCornerRadius,
            TitlebarHeight: SettingsGeometry.TitlebarHeight,
            BodyHeight: SettingsGeometry.BodyHeight,
            SidebarX: SettingsGeometry.SidebarX,
            SidebarY: SettingsGeometry.SidebarY,
            SidebarWidth: SettingsGeometry.SidebarWidth,
            SidebarHeight: SettingsGeometry.SidebarHeight,
            ContentX: SettingsGeometry.ContentX,
            ContentY: SettingsGeometry.ContentY,
            ContentWidth: SettingsGeometry.ContentWidth,
            ContentHeight: SettingsGeometry.ContentHeight,
            ContentHeaderHeight: SettingsGeometry.ContentHeaderHeight,
            ContentBodyY: SettingsGeometry.ContentBodyY,
            ContentBodyHeight: SettingsGeometry.ContentBodyHeight,
            ContentBodyPaddingTop: SettingsGeometry.ContentBodyPaddingTop,
            ContentBodyWithRegionsPaddingTop: SettingsGeometry.ContentBodyWithRegionsPaddingTop,
            ContentBodyPaddingX: SettingsGeometry.ContentBodyPaddingX,
            ContentBodyPaddingBottom: SettingsGeometry.ContentBodyPaddingBottom,
            PanelX: SettingsGeometry.PanelX,
            PanelNoRegionsY: SettingsGeometry.PanelNoRegionsY,
            PanelWithRegionsY: SettingsGeometry.PanelWithRegionsY,
            PanelSmallWidth: SettingsGeometry.PanelSmallWidth,
            PanelMediumWidth: SettingsGeometry.PanelMediumWidth,
            PanelWideWidth: SettingsGeometry.PanelWideWidth,
            PanelBorderWidth: SettingsGeometry.PanelBorderWidth,
            PanelPaddingX: SettingsGeometry.PanelPaddingX,
            PanelPaddingY: SettingsGeometry.PanelPaddingY,
            PanelTitleHeight: SettingsGeometry.PanelTitleHeight,
            PanelTitleBoundsHeight: SettingsGeometry.PanelTitleBoundsHeight,
            PanelTitlePaddingBottom: SettingsGeometry.PanelTitlePaddingBottom,
            PanelTitleMarginBottom: SettingsGeometry.PanelTitleMarginBottom,
            GeneralGridGap: SettingsGeometry.GeneralGridGap,
            GeneralTopGridHeight: SettingsGeometry.GeneralTopGridHeight,
            UnitsPanelWidth: SettingsGeometry.UnitsPanelWidth,
            UnitsPanelHeight: SettingsGeometry.UnitsPanelHeight,
            UpdatesPanelWidth: SettingsGeometry.UpdatesPanelWidth,
            UpdatesPanelHeight: SettingsGeometry.UpdatesPanelHeight,
            NativeUpdatesPanelHeight: SettingsGeometry.NativeUpdatesPanelHeight,
            PreviewPanelWidth: SettingsGeometry.PreviewPanelWidth,
            PreviewPanelHeight: SettingsGeometry.PreviewPanelHeight,
            PreviewPanelMarginTop: SettingsGeometry.PreviewPanelMarginTop,
            SupportPanelHeight: SettingsGeometry.SupportPanelHeight,
            OverlayControlsPanelHeight: SettingsGeometry.OverlayControlsPanelHeight,
            GarageOverlayControlsPanelHeight: SettingsGeometry.GarageOverlayControlsPanelHeight,
            BrowserSourcePanelWidth: SettingsGeometry.BrowserSourcePanelWidth,
            BrowserSourcePanelHeight: SettingsGeometry.BrowserSourcePanelHeight,
            BrowserSourceUrlHeight: SettingsGeometry.BrowserSourceUrlHeight,
            BrowserSourceSizeGapY: SettingsGeometry.BrowserSourceSizeGapY,
            BrowserSourceSizeHeight: SettingsGeometry.BrowserSourceSizeHeight,
            BrowserSourceCopyButtonTop: SettingsGeometry.BrowserSourceCopyButtonTop,
            BrowserSourceCopyButtonRight: SettingsGeometry.BrowserSourceCopyButtonRight,
            ContentMatrixWidth: SettingsGeometry.ContentMatrixWidth,
            ContentMatrixMinimumHeight: SettingsGeometry.ContentMatrixMinimumHeight,
            ContentMatrixPreviewHeight: SettingsGeometry.ContentMatrixPreviewHeight,
            ChatInputsWidth: SettingsGeometry.ChatInputsWidth,
            ChatInputsHeight: SettingsGeometry.ChatInputsHeight,
            StreamlabsPanelHeight: SettingsGeometry.StreamlabsPanelHeight,
            RegionSegmentShellHeight: SettingsGeometry.RegionSegmentShellHeight,
            RegionSegmentGap: SettingsGeometry.RegionSegmentGap,
            RegionSegmentPadding: SettingsGeometry.RegionSegmentPadding,
            RegionSegmentMarginBottom: SettingsGeometry.RegionSegmentMarginBottom,
            RegionTabsCropTopInset: SettingsGeometry.RegionTabsCropTopInset,
            RegionTabsCropExtraHeight: SettingsGeometry.RegionTabsCropExtraHeight,
            RegionSegmentHeight: SettingsGeometry.RegionSegmentHeight,
            RegionSegmentDefaultWidth: SettingsGeometry.RegionSegmentDefaultWidth,
            RegionSegmentGeneralWidth: SettingsGeometry.RegionSegmentGeneralWidth,
            RegionSegmentPreviewWidth: SettingsGeometry.RegionSegmentPreviewWidth,
            RegionSegmentStreamlabsWidth: SettingsGeometry.RegionSegmentStreamlabsWidth,
            SidebarTabX: SettingsGeometry.SidebarTabX,
            SidebarTabY: SettingsGeometry.SidebarTabY,
            SidebarTabWidth: SettingsGeometry.SidebarTabWidth,
            SidebarTabHeight: SettingsGeometry.SidebarTabHeight,
            SidebarTabStride: SettingsGeometry.SidebarTabStride,
            CloseButtonX: SettingsGeometry.CloseButtonX,
            CloseButtonY: SettingsGeometry.CloseButtonY,
            FieldRowDefaultWidth: SettingsGeometry.FieldRowDefaultWidth,
            FieldRowHeight: SettingsGeometry.FieldRowHeight,
            FieldRowOffsetY: SettingsGeometry.FieldRowOffsetY,
            FieldRowStride: SettingsGeometry.FieldRowStride,
            FieldLabelTopOffset: SettingsGeometry.FieldLabelTopOffset,
            FieldControlTopOffset: SettingsGeometry.FieldControlTopOffset,
            FieldStepperTopOffset: SettingsGeometry.FieldStepperTopOffset,
            FieldValueTopOffset: SettingsGeometry.FieldValueTopOffset,
            FieldLabelWidth: SettingsGeometry.FieldLabelWidth,
            FieldLabelHeight: SettingsGeometry.FieldLabelHeight,
            FieldValueHeight: SettingsGeometry.FieldValueHeight,
            PreviewSummaryOffsetY: SettingsGeometry.PreviewSummaryOffsetY,
            PreviewSummaryHeight: SettingsGeometry.PreviewSummaryHeight,
            PreviewSummaryTextTopOffset: SettingsGeometry.PreviewSummaryTextTopOffset,
            PreviewSummaryValueGapX: SettingsGeometry.PreviewSummaryValueGapX,
            PreviewModeOffsetY: SettingsGeometry.PreviewModeOffsetY,
            PreviewBodyTextOffsetY: SettingsGeometry.PreviewBodyTextOffsetY,
            PreviewBodyLineStride: SettingsGeometry.PreviewBodyLineStride,
            PreviewBodyLineHeight: SettingsGeometry.PreviewBodyLineHeight,
            PreviewBodyLineWidth: SettingsGeometry.PreviewBodyLineWidth,
            UpdatesActionButtonGapY: SettingsGeometry.UpdatesActionButtonGapY,
            SupportRawCaptureLabelWidth: SettingsGeometry.SupportRawCaptureLabelWidth,
            SupportButtonRowGapY: SettingsGeometry.SupportButtonRowGapY,
            SupportDescriptionOffsetX: SettingsGeometry.SupportDescriptionOffsetX,
            SupportDescriptionOffsetY: SettingsGeometry.SupportDescriptionOffsetY,
            SupportDescriptionWidth: SettingsGeometry.SupportDescriptionWidth,
            SupportDescriptionLineHeight: SettingsGeometry.SupportDescriptionLineHeight,
            SupportDescriptionLineStride: SettingsGeometry.SupportDescriptionLineStride,
            SupportStatusX: SettingsGeometry.SupportStatusX,
            SupportStatusY: SettingsGeometry.SupportStatusY,
            SupportStatusWidth: SettingsGeometry.SupportStatusWidth,
            SupportAnalysisRowHeight: SettingsGeometry.SupportAnalysisRowHeight,
            SupportAnalysisRowStride: SettingsGeometry.SupportAnalysisRowStride,
            SupportAnalysisLabelTopOffset: SettingsGeometry.SupportAnalysisLabelTopOffset,
            SupportAnalysisLabelWidth: SettingsGeometry.SupportAnalysisLabelWidth,
            SupportAnalysisLabelHeight: SettingsGeometry.SupportAnalysisLabelHeight,
            SupportAnalysisValueTopOffset: SettingsGeometry.SupportAnalysisValueTopOffset,
            SupportAnalysisValueWidth: SettingsGeometry.SupportAnalysisValueWidth,
            SupportAnalysisValueHeight: SettingsGeometry.SupportAnalysisValueHeight,
            SupportAnalysisToggleTopOffset: SettingsGeometry.SupportAnalysisToggleTopOffset,
            GaragePreviewStageHeight: SettingsGeometry.GaragePreviewStageHeight,
            GaragePreviewImageWidth: SettingsGeometry.GaragePreviewImageWidth,
            GaragePreviewImageHeight: SettingsGeometry.GaragePreviewImageHeight,
            ToggleRowWidth: SettingsGeometry.ToggleRowWidth,
            SliderRowWidth: SettingsGeometry.SliderRowWidth,
            StepperRowWidth: SettingsGeometry.StepperRowWidth,
            SegmentedRowWidth: SettingsGeometry.SegmentedRowWidth,
            ProviderChoiceRowWidth: SettingsGeometry.ProviderChoiceRowWidth,
            StreamlabsUrlRowWidth: SettingsGeometry.StreamlabsUrlRowWidth,
            TwitchChannelRowWidth: SettingsGeometry.TwitchChannelRowWidth,
            ToggleWidth: SettingsGeometry.ToggleWidth,
            ToggleHeight: SettingsGeometry.ToggleHeight,
            SliderWidth: SettingsGeometry.SliderWidth,
            SliderHeight: SettingsGeometry.SliderHeight,
            StepperWidth: SettingsGeometry.StepperWidth,
            StepperHeight: SettingsGeometry.StepperHeight,
            StepperButtonWidth: SettingsGeometry.StepperButtonWidth,
            StepperButtonHeight: SettingsGeometry.StepperButtonHeight,
            StepperGap: SettingsGeometry.StepperGap,
            SegmentedWidth: SettingsGeometry.SegmentedWidth,
            SegmentedHeight: SettingsGeometry.SegmentedHeight,
            SegmentedPadding: SettingsGeometry.SegmentedPadding,
            SegmentedChoiceGap: SettingsGeometry.SegmentedChoiceGap,
            WideSegmentedWidth: SettingsGeometry.WideSegmentedWidth,
            WideSegmentedHeight: SettingsGeometry.WideSegmentedHeight,
            WideSegmentedColumnWidth: SettingsGeometry.WideSegmentedColumnWidth,
            ProviderChoiceWidth: SettingsGeometry.ProviderChoiceWidth,
            StreamlabsInputWidth: SettingsGeometry.StreamlabsInputWidth,
            StreamlabsInputHeight: SettingsGeometry.StreamlabsInputHeight,
            TwitchInputWidth: SettingsGeometry.TwitchInputWidth,
            CopyButtonWidth: SettingsGeometry.CopyButtonWidth,
            CopyButtonHeight: SettingsGeometry.CopyButtonHeight,
            SupportBundleRowX: SettingsGeometry.SupportBundleRowX,
            SupportBundleRowY: SettingsGeometry.SupportBundleRowY,
            SupportBundleRowWidth: SettingsGeometry.SupportBundleRowWidth,
            SupportBundleRowHeight: SettingsGeometry.SupportBundleRowHeight,
            SupportBundleLabelWidth: SettingsGeometry.SupportBundleLabelWidth,
            SupportBundleLabelHeight: SettingsGeometry.SupportBundleLabelHeight,
            SupportBundleValueX: SettingsGeometry.SupportBundleValueX,
            SupportBundleValueY: SettingsGeometry.SupportBundleValueY,
            SupportBundleValueWidth: SettingsGeometry.SupportBundleValueWidth,
            SupportBundleValueHeight: SettingsGeometry.SupportBundleValueHeight,
            SupportBundleValueTopOffset: SettingsGeometry.SupportBundleValueTopOffset,
            SupportBundleValueHeightExtra: SettingsGeometry.SupportBundleValueHeightExtra,
            SupportBundleValueFontSize: SettingsGeometry.SupportBundleValueFontSize,
            FieldLabelFontSize: SettingsGeometry.FieldLabelFontSize,
            FieldValueFontSize: SettingsGeometry.FieldValueFontSize,
            ButtonFontSize: SettingsGeometry.ButtonFontSize,
            SegmentFontSize: SettingsGeometry.SegmentFontSize,
            SegmentLineHeight: SettingsGeometry.SegmentLineHeight,
            SegmentPaddingX: SettingsGeometry.SegmentPaddingX,
            PanelTitleFontSize: SettingsGeometry.PanelTitleFontSize,
            NativePanelTitleFontSize: SettingsGeometry.NativePanelTitleFontSize,
            MatrixContentInsetX: SettingsGeometry.MatrixContentInsetX,
            MatrixHeaderOffsetY: SettingsGeometry.MatrixHeaderOffsetY,
            MatrixFirstRowOffsetY: SettingsGeometry.MatrixFirstRowOffsetY,
            MatrixHeaderHeight: SettingsGeometry.MatrixHeaderHeight,
            MatrixRowHeight: SettingsGeometry.MatrixRowHeight,
            MatrixRowGap: SettingsGeometry.MatrixRowGap,
            MatrixPanelBottomPadding: SettingsGeometry.MatrixPanelBottomPadding,
            MatrixColumnGap: SettingsGeometry.MatrixColumnGap,
            MatrixCheckSize: SettingsGeometry.MatrixCheckSize,
            CheckSize: SettingsGeometry.CheckSize,
            MatrixControlContentWidth: SettingsGeometry.MatrixControlContentWidth,
            MatrixControlLabelWidth: SettingsGeometry.MatrixControlLabelWidth,
            MatrixControlGap: SettingsGeometry.MatrixControlGap,
            MatrixControlItemGap: SettingsGeometry.MatrixControlItemGap,
            MatrixControlCellPadding: SettingsGeometry.MatrixControlCellPadding,
            MatrixControlStepperWidth: SettingsGeometry.MatrixControlStepperWidth,
            MatrixControlStepperButtonWidth: SettingsGeometry.MatrixControlStepperButtonWidth,
            MatrixControlRowTopGap: SettingsGeometry.MatrixControlRowTopGap,
            MatrixControlRowHeight: SettingsGeometry.MatrixControlRowHeight,
            MatrixControlHeight: SettingsGeometry.MatrixControlHeight,
            MatrixControlStepperHeight: SettingsGeometry.MatrixControlStepperHeight,
            MatrixHeadHeight: SettingsGeometry.MatrixHeadHeight,
            BlockGridContentInsetX: SettingsGeometry.BlockGridContentInsetX,
            BlockGridHeaderOffsetY: SettingsGeometry.BlockGridHeaderOffsetY,
            BlockGridFirstRowOffsetY: SettingsGeometry.BlockGridFirstRowOffsetY,
            BlockGridPanelBottomPadding: SettingsGeometry.BlockGridPanelBottomPadding,
            BlockGridColumnGap: SettingsGeometry.BlockGridColumnGap,
            BlockGridRowHeight: SettingsGeometry.BlockGridRowHeight,
            BlockGridRowGap: SettingsGeometry.BlockGridRowGap,
            BlockGridSessionColumnStride: SettingsGeometry.BlockGridSessionColumnStride,
            BlockGridSessionCellsRightInset: SettingsGeometry.BlockGridSessionCellsRightInset,
            BlockGridVisibleCellRightInset: SettingsGeometry.BlockGridVisibleCellRightInset,
            BlockGridCheckSize: SettingsGeometry.BlockGridCheckSize,
            CompactMatrixRowGap: SettingsGeometry.CompactMatrixRowGap,
            CompactMatrixColumnGap: SettingsGeometry.CompactMatrixColumnGap,
            CompactMatrixPaddingY: SettingsGeometry.CompactMatrixPaddingY,
            CompactMatrixPaddingX: SettingsGeometry.CompactMatrixPaddingX,
            CompactMatrixHeadingHeight: SettingsGeometry.CompactMatrixHeadingHeight,
            CompactMatrixHeadingPaddingBottom: SettingsGeometry.CompactMatrixHeadingPaddingBottom,
            CompactMatrixHeadingMarginBottom: SettingsGeometry.CompactMatrixHeadingMarginBottom,
            CompactMatrixLegendGap: SettingsGeometry.CompactMatrixLegendGap,
            CompactMatrixRowHeight: SettingsGeometry.CompactMatrixRowHeight,
            ActionButtonMinimumWidth: SettingsGeometry.ActionButtonMinimumWidth,
            ActionButtonHeight: SettingsGeometry.ActionButtonHeight,
            ActionButtonGap: SettingsGeometry.ActionButtonGap,
            SmallActionButtonGap: SettingsGeometry.SmallActionButtonGap,
            CloseButtonWidth: SettingsGeometry.CloseButtonWidth,
            CloseButtonHeight: SettingsGeometry.CloseButtonHeight,
            UpdateCheckButtonWidth: SettingsGeometry.UpdateCheckButtonWidth,
            UpdatePrimaryButtonWidth: SettingsGeometry.UpdatePrimaryButtonWidth,
            SupportCreateBundleButtonWidth: SettingsGeometry.SupportCreateBundleButtonWidth,
            SupportOpenBundleButtonWidth: SettingsGeometry.SupportOpenBundleButtonWidth,
            GarageImportButtonWidth: SettingsGeometry.GarageImportButtonWidth,
            GarageClearButtonWidth: SettingsGeometry.GarageClearButtonWidth,
            StreamChatSaveButtonWidth: SettingsGeometry.StreamChatSaveButtonWidth,
            SessionColumnWidth: SettingsGeometry.SessionColumnWidth,
            CompactSessionColumnWidth: SettingsGeometry.CompactSessionColumnWidth,
            SessionCheckColumnWidth: SettingsGeometry.SessionCheckColumnWidth,
            SessionCheckColumnGap: SettingsGeometry.SessionCheckColumnGap,
            OverlayControlsPanelBottomPadding: SettingsGeometry.OverlayControlsPanelBottomPadding),
        OverlaySizes: new OverlaySizesGeometryContract(
            StandingsWidth: OverlaySizes.StandingsWidth,
            StandingsBrowserReviewWidth: OverlaySizes.StandingsBrowserReviewWidth,
            StandingsHeight: OverlaySizes.StandingsHeight,
            RelativeWidth: OverlaySizes.RelativeWidth,
            RelativeHeight: OverlaySizes.RelativeHeight,
            GapToLeaderWidth: OverlaySizes.GapToLeaderWidth,
            GapToLeaderHeight: OverlaySizes.GapToLeaderHeight,
            GapToLeaderMinimumWidth: OverlaySizes.GapToLeaderMinimumWidth,
            GapToLeaderGraphOnlyWidth: OverlaySizes.GapToLeaderGraphOnlyWidth,
            GapToLeaderTrendOnlyWidth: OverlaySizes.GapToLeaderTrendOnlyWidth,
            GapToLeaderMinimumHeight: OverlaySizes.GapToLeaderMinimumHeight,
            RelativeHeaderChromeCollapseHeight: OverlaySizes.RelativeHeaderChromeCollapseHeight,
            TrackMapWidth: OverlaySizes.TrackMapWidth,
            TrackMapHeight: OverlaySizes.TrackMapHeight,
            StreamChatWidth: OverlaySizes.StreamChatWidth,
            StreamChatHeight: OverlaySizes.StreamChatHeight,
            GarageCoverWidth: OverlaySizes.GarageCoverWidth,
            GarageCoverHeight: OverlaySizes.GarageCoverHeight,
            FuelCalculatorWidth: OverlaySizes.FuelCalculatorWidth,
            FuelCalculatorHeight: OverlaySizes.FuelCalculatorHeight,
            InputStateWidth: OverlaySizes.InputStateWidth,
            InputStateHeight: OverlaySizes.InputStateHeight,
            CarRadarWidth: OverlaySizes.CarRadarWidth,
            CarRadarHeight: OverlaySizes.CarRadarHeight,
            FlagsWidth: OverlaySizes.FlagsWidth,
            FlagsHeight: OverlaySizes.FlagsHeight,
            SessionWeatherWidth: OverlaySizes.SessionWeatherWidth,
            SessionWeatherHeight: OverlaySizes.SessionWeatherHeight,
            PitServiceWidth: OverlaySizes.PitServiceWidth,
            PitServiceHeight: OverlaySizes.PitServiceHeight),
        TableGeometry: new TableGeometryContract(
            BrowserWidthPadding: TableGeometry.BrowserWidthPadding,
            StandingsClassPositionWidth: TableGeometry.StandingsClassPositionWidth,
            StandingsCarNumberWidth: TableGeometry.StandingsCarNumberWidth,
            StandingsDriverWidth: TableGeometry.StandingsDriverWidth,
            StandingsClassGapWidth: TableGeometry.StandingsClassGapWidth,
            StandingsPreviousIntervalWidth: TableGeometry.StandingsPreviousIntervalWidth,
            StandingsFastestLapWidth: TableGeometry.StandingsFastestLapWidth,
            StandingsLastLapWidth: TableGeometry.StandingsLastLapWidth,
            StandingsPitStatusWidth: TableGeometry.StandingsPitStatusWidth,
            RelativePositionWidth: TableGeometry.RelativePositionWidth,
            RelativeDriverWidth: TableGeometry.RelativeDriverWidth,
            RelativeDeltaWidth: TableGeometry.RelativeDeltaWidth,
            RelativePitStatusWidth: TableGeometry.RelativePitStatusWidth,
            RelativeMinimumHeight: TableGeometry.RelativeMinimumHeight,
            RelativeHeightChrome: TableGeometry.RelativeHeightChrome,
            RelativeRowHeight: TableGeometry.RelativeRowHeight,
            RelativeRowGap: TableGeometry.RelativeRowGap));

    internal static class GapGraph
    {
        internal const int FrameInsetX = 12;
        internal const int FrameInsetY = 14;
        internal const int AxisWidth = 58;
        internal const int XAxisHeight = 17;
        internal const int EndpointLabelLaneWidth = 38;
        internal const int MetricsTableWidth = 220;
        internal const int MetricsTableGap = 10;
        internal const int MetricsMinimumPlotWidth = 260;
        internal const int MetricsMinimumTableHeight = 164;
        internal const int MetricsTableInset = 10;
        internal const int MetricsRowsTopOffset = 48;
        internal const int MetricsBottomPadding = 8;
        internal const int MetricsColumnGap = 6;
        internal const int MetricsRowMinHeight = 12;
        internal const int MetricsRowMaxHeight = 26;
        internal const bool MetricOnlyUsesFullFrame = true;
        internal const float BrowserPanelPaddingX = 10.5f;
        internal const float BrowserPanelPaddingY = 11.5f;
    }

    internal static class MetricRows
    {
        internal const int MinimumSimpleTelemetryHeight = 184;
        internal const int MinimumSimpleTelemetryWidth = 464;
        internal const int NonRaceSimpleTelemetryHeightReduction = 40;
        internal const int PitServiceMetricOnlyWidth = 454;
        internal const int MinimumFuelCalculatorHeight = 126;
        internal const int FuelNonRaceHeight = 184;
        internal const int MinimumChromeAdjustedHeight = 80;
        internal const int HeaderChromeHeight = 38;
        internal const int FooterChromeHeight = 32;
        internal const int BodyGap = 12;
        internal const int ContentPaddingX = 16;
        internal const int ContentPaddingTop = 12;
        internal const int ContentPaddingBottom = 14;
        internal const int CollapsedFooterReserveHeight = 8;
        internal const int FuelContentVerticalPadding = 26;
        internal const int FuelSectionTitleReserveHeight = 14;
        internal const int PlainRowHeight = 30;
        internal const int SegmentedRowHeight = 35;
        internal const float DirectionalRowHeight = 37.5f;
        internal const int RowGap = 5;
        internal const int SectionTitleHeight = 11;
        internal const int SectionTitleBottomGap = 4;
        internal const int SectionTitleInsetX = 4;
        internal const int SectionGap = 8;
        internal const int MetricListMinimumWidth = 420;
        internal const int RowRadius = 5;
        internal const int RowBorderWidth = 1;
        internal const int LabelColumnWidth = 124;
        internal const int LabelPaddingLeft = 10;
        internal const int LabelPaddingRight = 8;
        internal const int ValuePaddingLeft = 8;
        internal const int ValuePaddingRight = 10;
        internal const int ValueDividerWidth = 1;
        internal const int CellVerticalPadding = 6;
        internal const int ValueSegmentGap = 3;
        internal const int PitServiceSectionGap = 3;
        internal const int PitServiceContentChromeHeight = 70;
        internal const int MetricGridMinimumHeight = 80;
        internal const int MetricGridGap = 8;
        internal const int MetricGridTopReserve = 72;
        internal const int MetricGridBottomReserve = 34;
        internal const int MetricGridTitleHeight = 0;
        internal const int MetricGridTitleBottomGap = 0;
        internal const int MetricGridHeaderHeight = 20;
        internal const int MetricGridHeaderBottomGap = 4;
        internal const int MetricGridRowHeight = 29;
        internal const int MetricGridRowGap = 4;
        internal const int MetricGridCellInset = 4;
        internal const int MetricGridCellGap = 3;
        internal const int MetricGridCellMinimumWidth = 42;
        internal const int MetricGridCellHeight = 21;
    }

    internal static class StreamChat
    {
        internal const int OverlayWidth = 380;
        internal const int OverlayHeight = 520;
        internal const int HeaderHeight = 38;
        internal const int HeaderRightReserve = 46;
        internal const int CloseButtonSize = 22;
        internal const int CloseButtonRight = 10;
        internal const int CloseButtonTop = 8;
        internal const int ContentHorizontalPadding = 16;
        internal const int ContentTopPadding = 12;
        internal const int ContentBottomPadding = 14;
        internal const int RowGap = 8;
        internal const int RowMinHeight = 44;
        internal const int RowPaddingX = 10;
        internal const int RowPaddingY = 6;
        internal const int RowBorderWidth = 1;
        internal const int RowRadius = 5;
        internal const int HeadGap = 5;
        internal const int HeadHeight = 17;
        internal const int HeadTextGap = 2;
        internal const int BadgeGap = 3;
        internal const float BadgeMaxRowFraction = 0.36f;
        internal const int BadgeMinWidth = 22;
        internal const int BadgeMaxWidth = 42;
        internal const int BadgeHeight = 14;
        internal const int BadgePaddingX = 4;
        internal const int BadgeImageSize = 15;
        internal const int NameFontSize = 11;
        internal const float NameFontPointSize = 8.25f;
        internal const int NameFontWeight = 800;
        internal const int ChipGap = 4;
        internal const int ChipMaxWidth = 76;
        internal const int ChipHeight = 14;
        internal const int ChipPaddingX = 5;
        internal const int ChipRadius = 3;
        internal const int ChipFontSize = 9;
        internal const int TextFontSize = 13;
        internal const float TextFontPointSize = 9.75f;
        internal const float TextLineHeight = 16.25f;
        internal const int EmoteSize = 21;
        internal const int EmoteMarginTop = -3;
        internal const int EmoteMarginX = 1;
        internal const int EmoteMarginBottom = -5;
        internal const int AvailableHeightFallbackOffset = 42;
        internal const int MinimumAvailableHeight = 48;
        internal const int MaxRows = 36;
        internal const int RowBudget = 52;
    }

    internal static class InputState
    {
        internal const int RefreshIntervalMilliseconds = 50;
        internal const int MaximumTracePoints = 180;
        internal const int GraphOnlyBaseWidth = 380;
        internal const int RailOnlyBaseWidth = 276;
        internal const int CompactWidth = 312;
        internal const int CompactHeight = 156;
        internal const int CompactMaxWidth = 360;
        internal const int CompactMaxHeight = 170;
        internal const int ContentPaddingX = 16;
        internal const int ContentPaddingTop = 12;
        internal const int ContentPaddingBottom = 14;
        internal const int HeaderBandHeight = 38;
        internal const int CompactContentPaddingX = 7;
        internal const int CompactContentPaddingTop = 6;
        internal const int CompactContentPaddingBottom = 7;
        internal const int CompactHeaderBandHeight = 32;
        internal const int GraphMinimumWidth = 160;
        internal const int GraphNoRailMinimumWidth = 220;
        internal const int GraphRailGap = 18;
        internal const int CompactGraphMinimumWidth = 92;
        internal const int CompactRailMinimumWidth = 72;
        internal const int CompactGraphRailGap = 10;
        internal const int RailMinimumWidth = 96;
        internal const int RailPreferredMinimumWidth = 136;
        internal const float RailPreferredWidthFraction = 0.4f;
        internal const int RailMaximumWidth = 204;
        internal const int RailOnlyMaximumWidth = 240;
        internal const int RailPadding = 8;
        internal const int CompactRailPadding = 4;
        internal const int RailGap = 8;
        internal const int CompactRailGap = 4;
        internal const int BarsGap = 7;
        internal const int CompactBarsGap = 2;
        internal const int ReadoutsGap = 5;
        internal const int CompactReadoutsGap = 2;
        internal const int RailLabelColumnWidth = 42;
        internal const int CompactRailLabelColumnWidth = 28;
        internal const int RailColumnGap = 6;
        internal const int CompactRailColumnGap = 4;
        internal const int BarHeight = 25;
        internal const int CompactBarHeight = 16;
        internal const int BarTrackHeight = 12;
        internal const int CompactBarTrackHeight = 8;
        internal const int ReadoutHeight = 20;
        internal const int CompactReadoutHeight = 13;
        internal const int WheelHeaderHeight = 14;
        internal const int CompactWheelHeaderHeight = 12;
        internal const int WheelGap = 8;
        internal const int CompactWheelGap = 4;
        internal const int WheelMinimumHeight = 24;
        internal const int CompactWheelMinimumHeight = 16;
        internal const int WheelMaximumHeight = 78;
        internal const int CompactWheelMaximumHeight = 43;
        internal const int WheelSvgSize = 32;
        internal const int CompactWheelSvgSize = 28;
        internal const int GraphGridLines = 3;
        internal const int CompactRailHeightThreshold = 190;
        internal const int RailContentCompactHeightThreshold = 150;
    }

    internal static class Flags
    {
        internal const int RefreshIntervalMilliseconds = 250;
        internal const int MinimumWidth = 180;
        internal const int MinimumHeight = 96;
        internal const int MaximumWidth = 960;
        internal const int MaximumHeight = 420;
        internal const int OuterPadding = 8;
        internal const int CellGap = 8;
        internal const int CompactCellHeightThreshold = 92;
        internal const int CompactCellWidthThreshold = 132;
        internal const int LabelHeight = 18;
        internal const int CompactLabelHeight = 16;
        internal const int LabelInsetX = 2;
        internal const int LabelBottomInset = 1;
        internal const int FlagAreaMinimumHeight = 32;
        internal const int PoleMinimumInsetX = 12;
        internal const float PoleInsetFractionX = 0.16f;
        internal const int PoleTopOffset = 4;
        internal const int PoleBottomInset = 2;
        internal const int PoleShadowOffset = 1;
        internal const int PoleCompactStrokeWidth = 2;
        internal const int PoleStrokeWidth = 3;
        internal const int ClothLeftOffset = 1;
        internal const int ClothRightInset = 8;
        internal const int ClothMinimumWidth = 48;
        internal const int ClothMinimumHeight = 24;
        internal const float ClothAreaHeightFraction = 0.7f;
        internal const float ClothWidthHeightFraction = 0.58f;
        internal const float ClothTopFraction = 0.32f;
        internal const int ClothTopMinimum = 4;
        internal const float CompactWave = 3.5f;
        internal const float Wave = 5.5f;
        internal const int LabelFontSize = 11;
        internal const int CompactLabelFontSize = 10;
        internal const float NativeLabelPointSize = 8.5f;
        internal const float NativeCompactLabelPointSize = 7.5f;
        internal const int CheckeredColumns = 6;
        internal const int CheckeredRows = 4;
        internal const int StripeMinimumWidth = 8;
        internal const float StripeWidthFraction = 0.12f;
        internal const float CautionStripeStrideMultiplier = 2.5f;
        internal const float DebrisStripeStrideMultiplier = 2.2f;
        internal const float MeatballDiameterFraction = 0.44f;
        internal const float PathControlOneFraction = 0.28f;
        internal const float PathControlTwoFraction = 0.62f;
        internal const float PathBottomWaveFraction = 0.4f;
        internal const int GridTwoCountMaximum = 2;
        internal const int GridFourCountMaximum = 4;
        internal const int GridSixCountMaximum = 6;
        internal const int GridMaximumColumns = 4;
    }

    internal static class CanvasOverlays
    {
        internal const int TrackMapWidth = 360;
        internal const int TrackMapHeight = 360;
        internal const int CarRadarWidth = 300;
        internal const int CarRadarHeight = 300;
        internal const int GarageCoverWidth = 1280;
        internal const int GarageCoverHeight = 720;
        internal const int GarageCoverAspectWidth = 16;
        internal const int GarageCoverAspectHeight = 9;
        internal const bool GarageCoverBrowserOnly = true;
        internal const bool UseConfiguredCanvasBacking = true;
        internal const bool CoverImageObjectFitCover = true;
    }

    internal static class SettingsGeometry
    {
        internal const int DesignWidth = 1152;
        internal const int DesignHeight = 608;
        internal const int NativeCanvasOffsetX = 44;
        internal const int NativeCanvasOffsetY = 36;
        internal const int ShellWidth = 1152;
        internal const int ShellHeight = 608;
        internal const int ShellCornerRadius = 18;
        internal const int TitlebarHeight = 58;
        internal const int BodyHeight = 550;
        internal const int SidebarX = 20;
        internal const int SidebarY = 80;
        internal const int SidebarWidth = 190;
        internal const int SidebarHeight = 506;
        internal const int ContentX = 234;
        internal const int ContentY = 80;
        internal const int ContentWidth = 890;
        internal const int ContentHeight = 506;
        internal const int ContentHeaderHeight = 70;
        internal const int ContentBodyY = 152;
        internal const int ContentBodyHeight = 434;
        internal const int ContentBodyPaddingTop = 26;
        internal const int ContentBodyWithRegionsPaddingTop = 14;
        internal const int ContentBodyPaddingX = 26;
        internal const int ContentBodyPaddingBottom = 10;
        internal const int PanelX = 262;
        internal const int PanelNoRegionsY = 178;
        internal const int PanelWithRegionsY = 236;
        internal const int PanelSmallWidth = 392;
        internal const int PanelMediumWidth = 414;
        internal const int PanelWideWidth = 834;
        internal const int PanelBorderWidth = 1;
        internal const int PanelPaddingX = 22;
        internal const int PanelPaddingY = 18;
        internal const int PanelTitleHeight = 20;
        internal const int PanelTitleBoundsHeight = 30;
        internal const int PanelTitlePaddingBottom = 14;
        internal const int PanelTitleMarginBottom = 14;
        internal const int GeneralGridGap = 28;
        internal const int GeneralTopGridHeight = 156;
        internal const int UnitsPanelWidth = 392;
        internal const int UnitsPanelHeight = 132;
        internal const int UpdatesPanelWidth = 414;
        internal const int UpdatesPanelHeight = 156;
        internal const int NativeUpdatesPanelHeight = 156;
        internal const int PreviewPanelWidth = 612;
        internal const int PreviewPanelHeight = 196;
        internal const int PreviewPanelMarginTop = 28;
        internal const int SupportPanelHeight = 278;
        internal const int OverlayControlsPanelHeight = 266;
        internal const int GarageOverlayControlsPanelHeight = 200;
        internal const int BrowserSourcePanelWidth = 414;
        internal const int BrowserSourcePanelHeight = 132;
        internal const int BrowserSourceUrlHeight = 32;
        internal const int BrowserSourceSizeGapY = 8;
        internal const int BrowserSourceSizeHeight = 18;
        internal const int BrowserSourceCopyButtonTop = 101;
        internal const int BrowserSourceCopyButtonRight = 22;
        internal const int ContentMatrixWidth = 834;
        internal const int ContentMatrixMinimumHeight = 188;
        internal const int ContentMatrixPreviewHeight = 222;
        internal const int ChatInputsWidth = 650;
        internal const int ChatInputsHeight = 204;
        internal const int StreamlabsPanelHeight = 150;
        internal const int RegionSegmentShellHeight = 42;
        internal const int RegionSegmentGap = 12;
        internal const int RegionSegmentPadding = 6;
        internal const int RegionSegmentMarginBottom = 28;
        internal const int RegionTabsCropTopInset = 4;
        internal const int RegionTabsCropExtraHeight = 10;
        internal const int RegionSegmentHeight = 30;
        internal const int RegionSegmentDefaultWidth = 76;
        internal const int RegionSegmentGeneralWidth = 86;
        internal const int RegionSegmentPreviewWidth = 82;
        internal const int RegionSegmentStreamlabsWidth = 104;
        internal const int SidebarTabX = 34;
        internal const int SidebarTabY = 100;
        internal const int SidebarTabWidth = 164;
        internal const int SidebarTabHeight = 27;
        internal const int SidebarTabStride = 32;
        internal const int CloseButtonX = 1090;
        internal const int CloseButtonY = 18;
        internal const int FieldRowDefaultWidth = 346;
        internal const int FieldRowHeight = 34;
        internal const int FieldRowOffsetY = 63;
        internal const int FieldRowStride = 42;
        internal const int FieldLabelTopOffset = 9;
        internal const int FieldControlTopOffset = 3;
        internal const int FieldStepperTopOffset = 1;
        internal const int FieldValueTopOffset = 10;
        internal const int FieldLabelWidth = 126;
        internal const int FieldLabelHeight = 18;
        internal const int FieldValueHeight = 18;
        internal const int PreviewSummaryOffsetY = 63;
        internal const int PreviewSummaryHeight = 24;
        internal const int PreviewSummaryTextTopOffset = 2;
        internal const int PreviewSummaryValueGapX = 18;
        internal const int PreviewModeOffsetY = 91;
        internal const int PreviewBodyTextOffsetY = 133;
        internal const int PreviewBodyLineStride = 18;
        internal const int PreviewBodyLineHeight = 16;
        internal const int PreviewBodyLineWidth = 542;
        internal const int UpdatesActionButtonGapY = 12;
        internal const int SupportRawCaptureLabelWidth = 250;
        internal const int SupportButtonRowGapY = 12;
        internal const int SupportDescriptionOffsetX = 23;
        internal const int SupportDescriptionOffsetY = 195;
        internal const int SupportDescriptionWidth = 326;
        internal const int SupportDescriptionLineHeight = 16;
        internal const int SupportDescriptionLineStride = 16;
        internal const int SupportStatusX = 328;
        internal const int SupportStatusY = 446;
        internal const int SupportStatusWidth = 330;
        internal const int SupportAnalysisRowHeight = 31;
        internal const int SupportAnalysisRowStride = 37;
        internal const int SupportAnalysisLabelTopOffset = 3;
        internal const int SupportAnalysisLabelWidth = 260;
        internal const int SupportAnalysisLabelHeight = 14;
        internal const int SupportAnalysisValueTopOffset = 10;
        internal const int SupportAnalysisValueWidth = 32;
        internal const int SupportAnalysisValueHeight = 11;
        internal const int SupportAnalysisToggleTopOffset = 1;
        internal const int GaragePreviewStageHeight = 338;
        internal const int GaragePreviewImageWidth = 600;
        internal const int GaragePreviewImageHeight = 338;
        internal const int ToggleRowWidth = 328;
        internal const int SliderRowWidth = 354;
        internal const int StepperRowWidth = 354;
        internal const int SegmentedRowWidth = 332;
        internal const int ProviderChoiceRowWidth = 426;
        internal const int StreamlabsUrlRowWidth = 546;
        internal const int TwitchChannelRowWidth = 336;
        internal const int ToggleWidth = 56;
        internal const int ToggleHeight = 28;
        internal const int SliderWidth = 180;
        internal const int SliderHeight = 28;
        internal const int StepperWidth = 180;
        internal const int StepperHeight = 32;
        internal const int StepperButtonWidth = 34;
        internal const int StepperButtonHeight = 24;
        internal const int StepperGap = 6;
        internal const int SegmentedWidth = 154;
        internal const int SegmentedHeight = 30;
        internal const int SegmentedPadding = 3;
        internal const int SegmentedChoiceGap = 6;
        internal const int WideSegmentedWidth = 468;
        internal const int WideSegmentedHeight = 32;
        internal const int WideSegmentedColumnWidth = 88;
        internal const int ProviderChoiceWidth = 300;
        internal const int StreamlabsInputWidth = 420;
        internal const int StreamlabsInputHeight = 28;
        internal const int TwitchInputWidth = 210;
        internal const int CopyButtonWidth = 70;
        internal const int CopyButtonHeight = 30;
        internal const int SupportBundleRowX = 328;
        internal const int SupportBundleRowY = 326;
        internal const int SupportBundleRowWidth = 330;
        internal const int SupportBundleRowHeight = 34;
        internal const int SupportBundleLabelWidth = 110;
        internal const int SupportBundleLabelHeight = 18;
        internal const int SupportBundleValueX = 454;
        internal const int SupportBundleValueY = 325;
        internal const int SupportBundleValueWidth = 220;
        internal const int SupportBundleValueHeight = 18;
        internal const int SupportBundleValueTopOffset = 2;
        internal const int SupportBundleValueHeightExtra = 13;
        internal const float SupportBundleValueFontSize = 10.5f;
        internal const int FieldLabelFontSize = 13;
        internal const int FieldValueFontSize = 12;
        internal const int ButtonFontSize = 12;
        internal const int SegmentFontSize = 12;
        internal const int SegmentLineHeight = 14;
        internal const int SegmentPaddingX = 0;
        internal const int PanelTitleFontSize = 15;
        internal const int NativePanelTitleFontSize = 16;
        internal const int MatrixContentInsetX = 23;
        internal const int MatrixHeaderOffsetY = 63;
        internal const int MatrixFirstRowOffsetY = 83;
        internal const int MatrixHeaderHeight = 16;
        internal const int MatrixRowHeight = 22;
        internal const int MatrixRowGap = 4;
        internal const int MatrixPanelBottomPadding = 19;
        internal const int MatrixColumnGap = 12;
        internal const int MatrixCheckSize = 19;
        internal const int CheckSize = 19;
        internal const int MatrixControlContentWidth = 768;
        internal const int MatrixControlLabelWidth = 244;
        internal const int MatrixControlGap = 12;
        internal const int MatrixControlItemGap = 10;
        internal const int MatrixControlCellPadding = 12;
        internal const int MatrixControlStepperWidth = 220;
        internal const int MatrixControlStepperButtonWidth = 24;
        internal const int MatrixControlRowTopGap = 5;
        internal const int MatrixControlRowHeight = 56;
        internal const int MatrixControlHeight = 24;
        internal const int MatrixControlStepperHeight = 32;
        internal const int MatrixHeadHeight = 16;
        internal const int BlockGridContentInsetX = 19;
        internal const int BlockGridHeaderOffsetY = 44;
        internal const int BlockGridFirstRowOffsetY = 60;
        internal const int BlockGridPanelBottomPadding = 13;
        internal const int BlockGridColumnGap = 18;
        internal const int BlockGridRowHeight = 19;
        internal const int BlockGridRowGap = 3;
        internal const int BlockGridSessionColumnStride = 34;
        internal const int BlockGridSessionCellsRightInset = 105;
        internal const int BlockGridVisibleCellRightInset = 38;
        internal const int BlockGridCheckSize = 15;
        internal const int CompactMatrixRowGap = 3;
        internal const int CompactMatrixColumnGap = 18;
        internal const int CompactMatrixPaddingY = 12;
        internal const int CompactMatrixPaddingX = 18;
        internal const int CompactMatrixHeadingHeight = 17;
        internal const int CompactMatrixHeadingPaddingBottom = 8;
        internal const int CompactMatrixHeadingMarginBottom = 8;
        internal const int CompactMatrixLegendGap = 10;
        internal const int CompactMatrixRowHeight = 17;
        internal const int ActionButtonMinimumWidth = 70;
        internal const int ActionButtonHeight = 30;
        internal const int ActionButtonGap = 10;
        internal const int SmallActionButtonGap = 8;
        internal const int CloseButtonWidth = 30;
        internal const int CloseButtonHeight = 24;
        internal const int UpdateCheckButtonWidth = 76;
        internal const int UpdatePrimaryButtonWidth = 70;
        internal const int SupportCreateBundleButtonWidth = 132;
        internal const int SupportOpenBundleButtonWidth = 150;
        internal const int GarageImportButtonWidth = 112;
        internal const int GarageClearButtonWidth = 86;
        internal const int StreamChatSaveButtonWidth = 92;
        internal const int SessionColumnWidth = 104;
        internal const int CompactSessionColumnWidth = 24;
        internal const int SessionCheckColumnWidth = 100;
        internal const int SessionCheckColumnGap = 16;
        internal const int OverlayControlsPanelBottomPadding = 19;
    }

    internal static class OverlaySizes
    {
        internal const int StandingsWidth = 665;
        internal const int StandingsBrowserReviewWidth = 677;
        internal const int StandingsHeight = 313;
        internal const int RelativeWidth = 360;
        internal const int RelativeHeight = 308;
        internal const int GapToLeaderWidth = 654;
        internal const int GapToLeaderHeight = 336;
        internal const int GapToLeaderMinimumWidth = 360;
        internal const int GapToLeaderGraphOnlyWidth = 444;
        internal const int GapToLeaderTrendOnlyWidth = 360;
        internal const int GapToLeaderMinimumHeight = 196;
        internal const int RelativeHeaderChromeCollapseHeight = 34;
        internal const int TrackMapWidth = 360;
        internal const int TrackMapHeight = 360;
        internal const int StreamChatWidth = 380;
        internal const int StreamChatHeight = 520;
        internal const int GarageCoverWidth = 1280;
        internal const int GarageCoverHeight = 720;
        internal const int FuelCalculatorWidth = 503;
        internal const int FuelCalculatorHeight = 315;
        internal const int InputStateWidth = 520;
        internal const int InputStateHeight = 260;
        internal const int CarRadarWidth = 300;
        internal const int CarRadarHeight = 300;
        internal const int FlagsWidth = 270;
        internal const int FlagsHeight = 128;
        internal const int SessionWeatherWidth = 464;
        internal const int SessionWeatherHeight = 496;
        internal const int PitServiceWidth = 530;
        internal const int PitServiceHeight = 707;
    }

    internal static class TableGeometry
    {
        internal const int BrowserWidthPadding = 34;
        internal const int StandingsClassPositionWidth = 35;
        internal const int StandingsCarNumberWidth = 50;
        internal const int StandingsDriverWidth = 250;
        internal const int StandingsClassGapWidth = 60;
        internal const int StandingsPreviousIntervalWidth = 60;
        internal const int StandingsFastestLapWidth = 70;
        internal const int StandingsLastLapWidth = 70;
        internal const int StandingsPitStatusWidth = 48;
        internal const int RelativePositionWidth = 48;
        internal const int RelativeDriverWidth = 240;
        internal const int RelativeDeltaWidth = 70;
        internal const int RelativePitStatusWidth = 48;
        internal const int RelativeMinimumHeight = 160;
        internal const int RelativeHeightChrome = 96;
        internal const int RelativeRowHeight = 26;
        internal const int RelativeRowGap = 5;
    }
}
