#!/usr/bin/env python3
"""Generate C# constants from the shared overlay geometry contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = REPO_ROOT / "src" / "TmrOverlay.App" / "Overlays" / "BrowserSources" / "Assets" / "contracts" / "overlay-geometry.json"
OUTPUT_PATH = REPO_ROOT / "src" / "TmrOverlay.App" / "Overlays" / "OverlayGeometryContractValues.g.cs"


SECTION_RECORDS = {
    "gapGraph": "GapGraphGeometryContract",
    "metricRows": "MetricRowsGeometryContract",
    "streamChat": "StreamChatGeometryContract",
    "inputState": "InputStateGeometryContract",
    "flags": "FlagsGeometryContract",
    "canvasOverlays": "CanvasOverlaysGeometryContract",
    "settingsGeometry": "SettingsGeometryContract",
    "overlaySizes": "OverlaySizesGeometryContract",
    "tableGeometry": "TableGeometryContract",
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated C# output is stale.")
    args = parser.parse_args()

    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    output = render(contract)

    if args.check:
        try:
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)}: unable to read generated constants: {exc}", file=sys.stderr)
            return 1
        if current != output:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is stale; run tools/generate_overlay_geometry_constants.py",
                file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.write_text(output, encoding="utf-8")
    return 0


def render(contract: dict[str, Any]) -> str:
    missing = [section for section in SECTION_RECORDS if section not in contract]
    if missing:
        raise KeyError(f"overlay geometry contract missing sections: {', '.join(missing)}")

    lines: list[str] = [
        "// <auto-generated />",
        "// Generated by tools/generate_overlay_geometry_constants.py from",
        "// src/TmrOverlay.App/Overlays/BrowserSources/Assets/contracts/overlay-geometry.json.",
        "// Do not edit manually.",
        "",
        "namespace TmrOverlay.App.Overlays;",
        "",
        "internal static class OverlayGeometryContractValues",
        "{",
        "    public static OverlayGeometryContract Current { get; } = new(",
    ]

    sections = list(SECTION_RECORDS)
    for section_index, section in enumerate(sections):
        class_name = pascal(section)
        record_name = SECTION_RECORDS[section]
        suffix = "," if section_index < len(sections) - 1 else ");"
        lines.append(f"        {class_name}: new {record_name}(")
        keys = list(typed_section(contract, section))
        for key_index, key in enumerate(keys):
            punctuation = "," if key_index < len(keys) - 1 else f"){suffix}"
            lines.append(f"            {pascal(key)}: {class_name}.{pascal(key)}{punctuation}")

    lines.append("")
    for section_index, section in enumerate(sections):
        if section_index > 0:
            lines.append("")
        lines.extend(render_section(section, typed_section(contract, section)))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_section(section_name: str, values: dict[str, Any]) -> list[str]:
    lines = [
        f"    internal static class {pascal(section_name)}",
        "    {",
    ]
    for key, value in values.items():
        lines.append(f"        internal const {csharp_type(value)} {pascal(key)} = {csharp_literal(value)};")
    lines.append("    }")
    return lines


def typed_section(contract: dict[str, Any], section: str) -> dict[str, Any]:
    value = contract.get(section)
    if not isinstance(value, dict):
        raise TypeError(f"overlay geometry contract section {section!r} must be an object")
    for key, item in value.items():
        if not isinstance(item, (bool, int, float)):
            raise TypeError(f"overlay geometry contract value {section}.{key} must be numeric or boolean")
    return value


def pascal(value: str) -> str:
    parts: list[str] = []
    current = ""
    for char in value:
        if char in "_- ":
            if current:
                parts.append(current)
                current = ""
            continue
        if char.isupper() and current and not current[-1].isupper():
            parts.append(current)
            current = char
        else:
            current += char
    if current:
        parts.append(current)
    return "".join(part[:1].upper() + part[1:] for part in parts)


def csharp_type(value: Any) -> str:
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    return "float"


def csharp_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return f"{float(value):.6g}f"


if __name__ == "__main__":
    raise SystemExit(main())
